'''
Date: 19/01/2024
Desc: Pandas data processing of FANET dataset with multiprocessing.
      To get reliabilities of all links for each run in MCS adaptation simulations
'''

import pandas as pd # for data manipulation 
import numpy as np
# import matplotlib.pyplot as plt # for drawing graphs
import os, sys, glob, math
import time
from multiprocessing.pool import Pool
from itertools import repeat
from tqdm import tqdm
from scipy import special

def h_dist_calc(row):
    # Function to calc euclidean distance on every df row 
    h_dist = math.sqrt(row["U2G_Distance"]**2 - row["Height"]**2)
    return h_dist

def q_func(x):
    q = 0.5 - 0.5*special.erf(x / np.sqrt(2))
    return q

def friis_calc(P,freq,dist,ple):
    '''
    Friis path loss equation
    P = Tx transmit power
    freq = Signal frequency
    dist = Transmission distance
    ple = Path loss exponent
    '''
    propagation_speed = 299792458
    l = propagation_speed / freq
    h_pl = P * l**2 / (16*math.pi**2)
    P_Rx = h_pl * dist**(-ple)
    return P_Rx

def plos_calc(h_dist, height_tx, height_rx, env='suburban'):
    '''
    % This function implements the LoS probability model from the paper
    % "Blockage Modeling for Inter-layer UAVs Communications in Urban
    % Environments" 
    % param h_dist    : horizontal distance between Tx and Rx (m)
    % param height_tx : height of Tx
    % param height_rx : height of Rx
    '''
    if env == 'suburban':
        a1 = 0.1
        a2 = 7.5e-4
        a3 = 8
    
    delta_h = height_tx - height_rx
    # pow_factor = 2 * h_dist * math.sqrt(a1*a2/math.pi) + a1 # NOTE: Use this pow_factor if assuming PPP building dist.
    pow_factor = h_dist * math.sqrt(a1*a2) # NOTE: Use this pow_factor if assuming ITU-R assumptions.
    if delta_h == 0:
        p = (1 - math.exp((-(height_tx)**2) / (2*a3**2))) ** pow_factor
    else:
        delta_h = abs(delta_h)
        p = (1 - (math.sqrt(2*math.pi)*a3 / delta_h) * abs(q_func(height_tx/a3) - q_func(height_rx/a3))) ** pow_factor
    return p

def sinr_lognormal_approx(h_dist, height, env='suburban'):
    '''
    To approximate the SNR from signal considering multipath fading and shadowing
    Assuming no interference due to CSMA, and fixed noise
    Inputs:
    h_dist = Horizontal Distance between Tx and Rx
    height = Height difference between Tx and Rx
    env = The operating environment (currently only suburban supported)
    '''
    # Signal properties
    P_Tx_dBm = 20 # Transmit power of 
    P_Tx = 10**(P_Tx_dBm/10) / 1000
    freq = 2.4e9 # Channel frequency (Hz)
    noise_dBm = -86
    noise = 10**(noise_dBm/10) / 1000
    if env == "suburban":
        # ENV Parameters Constants ----------------------------------
        # n_min = 2
        # n_max = 2.75
        # K_dB_min = 7.8
        # K_dB_max = 17.5
        # K_min = 10**(K_dB_min/10)
        # K_max = 10**(K_dB_max/10)
        # alpha = 11.25 # Env parameters for logarithm std dev of shadowing 
        # beta = 0.06 # Env parameters for logarithm std dev of shadowing 
        n_min = 2
        n_max = 2.75
        K_dB_min = 1.4922
        K_dB_max = 12.2272
        K_min = 10**(K_dB_min/10)
        K_max = 10**(K_dB_max/10)
        alpha = 11.1852 # Env parameters for logarithm std dev of shadowing 
        beta = 0.06 # Env parameters for logarithm std dev of shadowing 
        # -----------------------------------------------------------
    # Calculate fading parameters
    PLoS = plos_calc(h_dist, 0, height, env='suburban')
    theta_Rx = math.atan2(height, h_dist) * 180 / math.pi # Elevation angle in degrees
    ple = (n_min - n_max) * PLoS + n_max # Path loss exponent
    sigma_phi_dB = alpha*math.exp(-beta*theta_Rx)
    sigma_phi = 10**(sigma_phi_dB/10) # Logarithmic std dev of shadowing
    K = K_min * math.exp(math.log(K_max/K_min) * PLoS**2)
    omega = 1 # Omega of NCS (Rician)
    dist = math.sqrt(h_dist**2 + height**2)
    P_Rx = friis_calc(P_Tx, freq, dist, ple)
    # Approximate L-NCS RV (which is the SNR) as lognormal
    eta = math.log(10) / 10
    mu_phi = 10*math.log10(P_Rx)
    E_phi = math.exp(eta*mu_phi + eta**2*sigma_phi**2/2) # Mean of shadowing RV
    var_phi = math.exp(2*eta*mu_phi+eta**2*sigma_phi**2)*(math.exp(eta**2*sigma_phi**2)-1) # Variance of shadowing RV
    E_chi = (special.gamma(1+1)/(1+K))*special.hyp1f1(-1,1,-K)*omega
    var_chi = (special.gamma(1+2)/(1+K)**2)*special.hyp1f1(-2,1,-K)*omega**2 - E_chi**2
    E_SNR = E_phi * E_chi / noise # Theoretical mean of SINR
    var_SNR = ((var_phi+E_phi**2)*(var_chi+E_chi**2) - E_phi**2 * E_chi**2) / noise**2
    std_dev_SNR = math.sqrt(var_SNR)
    # sigma_ln = math.sqrt(math.log(var_SNR/E_SNR**2 + 1))
    # mu_ln = math.log(E_SNR) - sigma_ln**2/2
    return E_SNR, std_dev_SNR

def compile_micro_sim_data_v2(file_list, video=False):
    '''
    Function to compile data from the CSV files generated by each micro-simulation
    Update: To specifically return the rx_df, tx_df, mon_df and pd_df in lists, so that specific dfs can be accessed (instead of aggregating UAV dfs)
    Input: file_list - List of simulation files belonging to a certain scenario (micro-sim)
            video - flag to indicate whether to compile video data
    Output: concatenates the raw data to UL and DL dataframes
    '''
    # Specify dtypes to save memory
    tx_df_dtypes = {"TxTime": np.float32, "Packet_Name": "category", "Packet_Seq": np.uint32, "Bytes": np.uint16, "Dest_Addr": 'category'}
    rx_df_dtypes = {"RxTime": np.float64, "TxTime": np.float32,	"Packet_Name": "str", "Bytes": np.uint16, "RSSI": 'str', "U2G_SINR": np.float32, "U2U_SINR": np.float32, 
                    "U2G_BER": np.float32, "U2U_BER": np.float32, "Src_Addr": 'category', "Dest_Addr": 'category', "Hop_Count": np.uint8, "Delay": np.float32, 
                    "Queueing_Time": np.float32, "Backoff_Time": np.float32, "U2G_Distance": np.float32, "Retry_Count": np.uint8}
    pd_df_dtypes = {"RxTime": np.float64, "TxTime": np.float32,	"Packet_Name": "str", "Bytes": np.uint16, "RSSI": 'str', "U2G_SINR": np.float32, "U2U_SINR": np.float32, 
                    "U2G_BER": np.float32, "U2U_BER": np.float32, "Delay": np.float32, "Queueing_Time": np.float32, "Backoff_Time": np.float32, "U2G_Distance": np.float16,
                    "Has_Bit_Error": np.uint8, "Packet_Drop_Reason": 'category'}

    # Let's get the GCS dfs ===============================================================
    gcs_rx_file = [file for file in file_list if ('_GCS-Rx.csv' in file)]
    gcs_tx_file = [file for file in file_list if ('_GCS-Tx.csv' in file)]
    gcs_mon_file = [file for file in file_list if ('_GCS-Wlan.csv' in file)]
    gcs_pd_file = [file for file in file_list if ('_GCS-PacketDrop.csv' in file)]
    if len(gcs_rx_file) > 0:
        gcs_rx_df = pd.read_csv(gcs_rx_file[0], dtype=rx_df_dtypes)
    else:
        print("GCS RX File Missing")
        print(file_list[0])
    if len(gcs_tx_file) > 0:
        gcs_tx_df = pd.read_csv(gcs_tx_file[0], dtype=tx_df_dtypes)
    else:
        print("GCS TX File Missing")
        print(file_list[0])
    if len(gcs_pd_file) > 0:
        gcs_pd_df = pd.read_csv(gcs_pd_file[0], dtype=pd_df_dtypes)
    else:
        print("GCS PD File Missing")
        print(file_list[0])
    if len(gcs_mon_file) > 0:
        gcs_mon_df = pd.read_csv(gcs_mon_file[0]) # Mon file is optional
        gcs_mon_df["Addr"] = "192.168.0.1"
    else: 
        gcs_mon_df = None

    # Let's get the GW dfs ===============================================================
    gw_rx_file = [file for file in file_list if (('_GW-Rx' in file))]
    gw_tx_file = [file for file in file_list if (('_GW-Tx' in file))]
    gw_mon_file = [file for file in file_list if (('_GW-Wlan' in file))]
    gw_pd_file = [file for file in file_list if (('_GW-PacketDrop' in file))]
    if len(gw_rx_file) > 0:
        gw_rx_df = pd.read_csv(gw_rx_file[0], dtype=rx_df_dtypes)
    else:
        print("GW RX File Missing")
        print(file_list[0])
    if len(gw_tx_file) > 0:
        gw_tx_df = pd.read_csv(gw_tx_file[0], dtype=tx_df_dtypes)
    else:
        print("GW TX File Missing")
        print(file_list[0])
    if len(gw_pd_file) > 0:
        gw_pd_df = pd.read_csv(gw_pd_file[0], dtype=pd_df_dtypes)
    else:
        print("GW PD File Missing")
        print(file_list[0])
    if len(gw_mon_file) > 0:
        gw_mon_df = pd.read_csv(gw_mon_file[0]) # Mon file is optional
        gw_mon_df["Addr"] = "192.168.0.2"
    else:
        gw_mon_df = None

    # Let's get the UAVs dfs ===============================================================
    uavs_rx_df_list = []
    uavs_tx_df_list = []
    uavs_mon_df_list = []
    uavs_pd_df_list = []
    uav_rx_files = [file for file in file_list if (('_UAV-' in file) and ('-Rx' in file))]
    uav_tx_files = [file for file in file_list if (('_UAV-' in file) and ('-Tx' in file))]
    uav_mon_files = [file for file in file_list if (('_UAV-' in file) and ('Wlan' in file))]
    uav_pd_files = [file for file in file_list if (('_UAV-' in file) and ('PacketDrop' in file))]
    uav_rx_files.sort()
    uav_tx_files.sort()
    uav_mon_files.sort()
    uav_pd_files.sort()
    if len(uav_rx_files) > 0:
        for uav_rx_file in uav_rx_files:
            uavs_rx_df_list.append(pd.read_csv(uav_rx_file, dtype=rx_df_dtypes))
    else:
        print("UAV RX File(s) Missing")
        print(file_list[0])
    if len(uav_tx_files) > 0:
        for uav_tx_file in uav_tx_files:
            uavs_tx_df_list.append(pd.read_csv(uav_tx_file, dtype=tx_df_dtypes))
    else:
        print("UAV TX File(s) Missing")
        print(file_list[0])
    if len(uav_pd_files) > 0:
        for uav_pd_file in uav_pd_files:
            uavs_pd_df_list.append(pd.read_csv(uav_pd_file, dtype=pd_df_dtypes))
    else:
        print("UAV PD File(s) Missing")
        print(file_list[0])
    if len(uav_mon_files) > 0: # UAV mon files are optional now
        uav_member_index = 3
        for uav_mon_file in uav_mon_files:
            uav_mon_df = pd.read_csv(uav_mon_file)
            uav_mon_df["Addr"] = "192.168.0." + str(uav_member_index)
            uavs_mon_df_list.append(uav_mon_df)
            uav_member_index += 1
    else:
        uavs_mon_df_list = []

    rx_df_list = [gcs_rx_df, gw_rx_df] + uavs_rx_df_list
    tx_df_list = [gcs_tx_df, gw_tx_df] + uavs_tx_df_list
    pd_df_list = [gcs_pd_df, gw_pd_df] + uavs_pd_df_list
    mon_df_list = [gcs_mon_df, gw_mon_df] + uavs_mon_df_list

    # If video data available, compile it
    if video:
        gcs_video_rx_file = [file for file in file_list if ('_GCS-Video-Rx.csv' in file)]
        gw_video_tx_file = [file for file in file_list if ('_GW-Video-Tx.csv' in file)]
        gw_video_pd_file = [file for file in file_list if ('_GW-Video-PacketDrop.csv' in file)]
        if len(gcs_video_rx_file) > 0:
            gcs_video_rx_df = pd.read_csv(gcs_video_rx_file[0], dtype=rx_df_dtypes)
        else:
            print("GCS VIDEO RX File Missing")
            print(file_list[0])
        if len(gw_video_tx_file) > 0:
            gw_video_tx_df = pd.read_csv(gw_video_tx_file[0], dtype=tx_df_dtypes)
        else:
            print("GW VIDEO TX File Missing")
            print(file_list[0])
        if len(gw_video_pd_file) > 0:
            gw_video_pd_df = pd.read_csv(gw_video_pd_file[0], dtype=pd_df_dtypes)
        else:
            print("GW VIDEO PD File Missing")
            print(file_list[0])
        video_df_list = [gw_video_tx_df, gcs_video_rx_df, gw_video_pd_df] # For video packets

    if not video:
        return rx_df_list, tx_df_list, pd_df_list, mon_df_list
    else:
        return rx_df_list, tx_df_list, pd_df_list, mon_df_list, video_df_list

def process_throughput_sliding_window_time_v2(rx_df, pd_df, winSize, stride, max_time, uav_speed):
    '''
    Function to calculate throughput data for a DataFrame based on sliding window measured by time duration
    The sliding window will slide by "stride" seconds
    winSize is the sliding window size (in seconds)
    maxTime is the max simulation time to consider for calculating the throughput (seconds)
    delay_threshold is the threshold to consider for delay exceeded
    rx_df - The RELIABLE rcvd DF of interest
    pd_df - The packet drop df of transmitter, to get measured reliability
    Return: A DataFrame of throughput samples with its associated horizontal distance
    NOTE: Assigns horizontal distance according to UAV speed, with time taken as the end of the time window.
    NOTE: Make sure rx_df has no duplicates and have delay exceeded packets filtered out
    ''' 
    throughput_list = []
    # rx_df["Delay"] = rx_df['RxTime']-rx_df['TxTime'] # NOTE: Should be done before funtion
    
    # If the max time is less than window size, just take one measure of throughput with available time
    if max_time < winSize: 
        totalBytes = rx_df["Bytes"].sum()
        throughput = totalBytes / max_time
        numReliable = len(rx_df)
        numSent = len(rx_df) + len(pd_df)
        HDist = uav_speed * max_time
        return pd.DataFrame([{"Time": max_time, "Horizontal_Distance": HDist, "Throughput": throughput, "Measured_Reliability": numReliable/numSent}])
    
    # Slide the time window
    for i in range(math.ceil((max_time - winSize) / stride)):
        rx_df_in_range = rx_df.loc[(rx_df["RxTime"] >= (i*stride)) & (rx_df["RxTime"] < (i*stride+winSize))] # Get rcvd packets within time window
        pd_df_in_range = pd_df.loc[(pd_df["RxTime"] >= (i*stride)) & (pd_df["RxTime"] < (i*stride+winSize))] # Get dropped packets within time window (we base it on time of drop - 'RxTime')
        if not (rx_df_in_range.empty and pd_df_in_range.empty):
            totalBytes = rx_df_in_range["Bytes"].sum()
            throughput = totalBytes / winSize
            numReliable = len(rx_df_in_range)
            numSent = len(rx_df_in_range) + len(pd_df_in_range)
            HDist = uav_speed * (i*stride+winSize)
            throughput_list.append({"Time": i*stride+winSize, "Horizontal_Distance": HDist, "Throughput": throughput, "Measured_Reliability": numReliable/numSent})
    return pd.DataFrame(throughput_list)

def process_scenario_v4(scenario_path, save_path, num_processes, 
                        dl_delay_threshold, ul_delay_threshold, vid_delay_threshold=0):
    '''
    Modified: To process all different runs of each sccenario (for measured throughput while UAV moving)
    dl indicates Downlink. Likewise for ul (Uplink) and vid (Video)
    slot_size: the length of the slot size in seconds
    stride: The sliding window will slide by "stride" seconds
    NOTE: If vid_delay_threshold = 0 (default), then the script will consider no video data to process!!!
    '''
    scenario = scenario_path.split("/")[-1]

    # UNCOMMENT BELOW TO ONLY PROCESS SCENARIOS WHERE THE SAVE_PATH DIR IS NOT YET CREATED
    # Create save file directory if not created
    if not os.path.isdir(os.path.join(save_path, scenario)):
        os.mkdir(os.path.join(save_path, scenario))
        print(scenario)
    # else: # UNCOMMENT TO SKIP CREATED DIRS
    #     return

    metric_list = []
    runs = sorted(glob.glob("{}/Run-*_GCS-Tx.csv".format(scenario_path))) # Get the different runs for each scenario
    run_number = [run.split('/')[-1].split("_")[0].split("-")[-1] for run in runs]
    run_file_path = os.path.join(scenario_path, "Run-{}_*.csv")
    with Pool(num_processes) as pool:
        for result in pool.starmap(process_run, zip(run_number, repeat(run_file_path), repeat(dl_delay_threshold), repeat(ul_delay_threshold), repeat(vid_delay_threshold))):
            metric_list.append({"Run": result[0], "Total_Reliability_DL": result[1], "Total_Delay_Excd_DL": result[2], "Total_Incr_Rcvd_DL": result[3], "Total_Q_Overflow_DL": result[4],
                                "Total_Reliability_UL": result[5], "Total_Delay_Excd_UL": result[6], "Total_Incr_Rcvd_UL": result[7], "Total_Q_Overflow_UL": result[8],
                                "Total_Reliability_VID": result[9], "Total_Delay_Excd_VID": result[10], "Total_Incr_Rcvd_VID": result[11], "Total_Q_Overflow_VID": result[12]})
    
    # Save metrics of each run to file
    metric_df = pd.DataFrame(metric_list)
    metric_df.to_csv(os.path.join(save_path, scenario, "Simulation_Results.csv"), index=False)

    return
    
def process_run(run_number, file_path, dl_delay_threshold, ul_delay_threshold, vid_delay_threshold=0):
    '''
    Provide file_path such that the files for a particular run number can be identified using glob.glob(file_path.format(run_number))
    '''
    run_files = glob.glob(file_path.format(run_number)) # Get list of csv files belonging to this scenario

    if vid_delay_threshold == 0:
        rx_df_list, tx_df_list, pd_df_list, mon_df_list = compile_micro_sim_data_v2(run_files, video=False)
    elif vid_delay_threshold > 0:
        rx_df_list, tx_df_list, pd_df_list, mon_df_list, video_df_list = compile_micro_sim_data_v2(run_files, video=True)

    # Sort out which df is which
    gcs_rx_df = rx_df_list[0].copy()
    gcs_tx_df = tx_df_list[0]
    gcs_pd_df = pd_df_list[0]
    
    uavs_tx_df = pd.concat(tx_df_list[1:len(tx_df_list)], ignore_index=True) # Includes GW Tx DF and all UAVs Tx DFs
    uavs_pd_df = pd.concat(pd_df_list[1:len(pd_df_list)], ignore_index=True)
    
    # Get the DL reliable packets
    num_dl_reliable = 0
    num_dl_delay_excd = 0
    # Remember, the RX DFs in rx_df_list is [GCS, Gateway, UAV-0, UAV-1, ...]
    for i in range(1,len(rx_df_list)):
        uav_rx_df = rx_df_list[i].copy()
        if not uav_rx_df.empty:
            uav_rx_df["Delay"] = uav_rx_df['RxTime']-uav_rx_df['TxTime'] # Calc delay of packets received
            uav_rx_reliable_df = uav_rx_df.loc[(uav_rx_df["Delay"] <= dl_delay_threshold)] # Get reliable packets
            uav_rx_delay_excd_df = uav_rx_df.loc[(uav_rx_df["Delay"] > dl_delay_threshold)] # Get delay excd packets
            num_dl_reliable += len(uav_rx_reliable_df)
            num_dl_delay_excd += len(uav_rx_delay_excd_df)
    num_dl_sent = len(gcs_tx_df)
    num_dl_incr_rcvd = len(gcs_pd_df.loc[gcs_pd_df["Packet_Drop_Reason"] == "RETRY_LIMIT_REACHED"]) # Get no. of incr rcvd packets
    num_dl_queue_overflow = len(gcs_pd_df.loc[gcs_pd_df["Packet_Drop_Reason"] == "QUEUE_OVERFLOW"]) # Get no. of q overflow packets
    dl_reliability = num_dl_reliable / num_dl_sent
    dl_delay_excd = num_dl_delay_excd / num_dl_sent
    dl_incr_rcvd = num_dl_incr_rcvd / num_dl_sent
    dl_queue_overflow = num_dl_queue_overflow / num_dl_sent

    # Get the UL reliable packets
    gcs_rx_df["Delay"] = gcs_rx_df['RxTime']-gcs_rx_df['TxTime'] # Calc delay of packets received
    gcs_rx_reliable_df = gcs_rx_df.loc[(gcs_rx_df["Delay"] <= ul_delay_threshold)] # Get reliable packets
    gcs_rx_delay_excd_df = gcs_rx_df.loc[(gcs_rx_df["Delay"] > ul_delay_threshold)] # Get delay exceeded packets
    num_ul_reliable = len(gcs_rx_reliable_df)
    num_ul_delay_excd = len(gcs_rx_delay_excd_df)
    num_ul_incr_rcvd = len(uavs_pd_df.loc[uavs_pd_df["Packet_Drop_Reason"] == "RETRY_LIMIT_REACHED"]) # Get no. of incr rcvd packets
    num_ul_queue_overflow = len(uavs_pd_df.loc[uavs_pd_df["Packet_Drop_Reason"] == "QUEUE_OVERFLOW"]) # Get no. of q overflow packets
    num_ul_sent = len(uavs_tx_df)
    ul_reliability = num_ul_reliable / num_ul_sent
    ul_delay_excd = num_ul_delay_excd / num_ul_sent
    ul_incr_rcvd = num_ul_incr_rcvd / num_ul_sent
    ul_queue_overflow = num_ul_queue_overflow / num_ul_sent

    # Get the Video reliable packets
    if vid_delay_threshold > 0:
        video_tx_df = video_df_list[0]
        video_rx_df = video_df_list[1]
        video_pd_df = video_df_list[2]
        video_rx_df["Delay"] = video_rx_df['RxTime']-video_rx_df['TxTime'] # Calc delay of packets received
        video_rx_reliable_df = video_rx_df.loc[(video_rx_df["Delay"] <= vid_delay_threshold)] # Get reliable packets
        # Get video metric for each run
        num_vid_delay_excd = len(video_rx_df.loc[(video_rx_df["Delay"] > vid_delay_threshold)]) # Get no. of delay exceeded packets
        num_vid_incr_rcvd = len(video_pd_df.loc[video_pd_df["Packet_Drop_Reason"] == "RETRY_LIMIT_REACHED"]) # Get no. of incr rcvd packets
        num_vid_queue_overflow = len(video_pd_df.loc[video_pd_df["Packet_Drop_Reason"] == "QUEUE_OVERFLOW"]) # Get no. of q overflow packets
        num_vid_reliable = len(video_rx_reliable_df)
        num_vid_sent = len(video_tx_df)
        vid_reliability = num_vid_reliable / num_vid_sent
        vid_delay_excd = num_vid_delay_excd / num_vid_sent
        vid_incr_rcvd = num_vid_incr_rcvd / num_vid_sent
        vid_queue_overflow = num_vid_queue_overflow / num_vid_sent
    else:
        vid_reliability = np.nan
        vid_delay_excd = np.nan
        vid_incr_rcvd = np.nan
        vid_queue_overflow = np.nan
        
    return (run_number, dl_reliability, dl_delay_excd, dl_incr_rcvd, dl_queue_overflow, 
            ul_reliability, ul_delay_excd, ul_incr_rcvd, ul_queue_overflow, 
            vid_reliability, vid_delay_excd, vid_incr_rcvd, vid_queue_overflow)

if __name__ == "__main__":
    '''
    MAKE SURE TO SET "GX_GCS" and "sending_interval_range" in function process_sim_data_v2
    '''
    # sim_root_path = "/media/research-student/One Touch/FANET_Dataset/Dataset_NP10000_DJISpark/mcs_adaptation_results/proposed_calibrated_precision"
    # save_path = "/media/research-student/One Touch/FANET_Dataset/Dataset_NP10000_DJISpark/mcs_adaptation_results/proposed_calibrated_precision_processed"
    sim_root_path = "/media/research-student/KingstonSSD/mcs_adaptation_results/nn_calibrated_specificity_999"
    save_path = "/media/research-student/KingstonSSD/mcs_adaptation_results/nn_calibrated_specificity_999_processed"
    # sim_root_path = "/home/clow0003/Reuben_ws/FANET_Dataset/mcs_adaptation_results/snr_based_max_pkt_size_99"
    # save_path = "/home/clow0003/Reuben_ws/FANET_Dataset/mcs_adaptation_results/snr_based_max_pkt_size_99_processed"

    dl_delay_threshold = 0.04
    ul_delay_threshold = 0.04
    vid_delay_threshold = 1 # NOTE: Set to zero if no video data
    
    scenario_list = [f.path for f in os.scandir(sim_root_path) if f.is_dir()] # Get list of "unique" scenarios

    # For each scenario, extract the UL and DL raw data
    num_processes = 32
    # For each scenario, extract the UL and DL raw data
    for scenario_path in scenario_list:
         process_scenario_v4(scenario_path, save_path, num_processes, 
                             dl_delay_threshold, ul_delay_threshold, vid_delay_threshold)


    
