# Date: 30/08/2023
# Modified FANET_Dataset_with_Video.ini to use pcap CSV files as a way of passing in packet size and sending interval from pcap files
[General]

[Config Height_Adaptation]
description = Proposed USI Adaptation for Reliability Requirement of 99%
network = fanet_adhoc_hosts_pcap
#record-eventlog = true

# --------------------- TRAINING DATASET ----------------------------------
*.numPacketsRecord = ${NPR=-1} # NPR set to -1 to indicate record all packets sent
*.numHosts = ${N=7}
*.gcsX = ${GX=0} # X coord of GCS, in m
*.gcsY = ${GY=0} # Y coord of GCS, in m
*.uavRadius = ${R=5}
*.gcsSendingInterval = ${EGSI=20} 
*.videoBitRate = ${VBR=2} # In Mbps
*.videoPacketSize = ${VPS=1450} # In bytes (with header of 64 bytes)
*.videoSendingInterval = ${VSI=($VPS) * 8 * 0.001 / ($VBR)} # In ms
.dlPcapCsvFilePath = ${DLPCSV="/home/clow0003/Reuben_ws/uav_traffic_csv/djispark_dl.csv"} 
.ulPcapCsvFilePath = ${ULPCSV="/home/clow0003/Reuben_ws/uav_traffic_csv/djispark_ul.csv"} 
.vidPcapCsvFilePath = ${VIDPCSV="/home/clow0003/Reuben_ws/uav_traffic_csv/djispark_vid.csv"} 

*.modulation = ${MCS="BPSK"} # The MCS will be set by the scenario script. This is just to fill in the parameter
*.MCSBitrate = ${BR=6.5 ! MCS} # The MCS will be set by the scenario script. This is just to fill in the parameter
*.uavSendingInterval = ${EUSI=10} # The USI will be set by the scenario script. This is just to fill in the parameter

# NOTE: The test cases for both 99% and 99.9% reliability are the same
*.uavSpeed = ${USP=6} # UAV speed in m/s
*.initHeight = ${IH=180} # Initial height (of MDP) in m
# *.simTime = ${SIM=26.66666666666667,34.833333333333364,22.000000000000014,19.166666666666657,22.500000000000007,57.33333333333332, \
#                   51.666666666666664,40.0,38.5,25.500000000000025,23.16666666666667,25.333333333333368,95.00000000000017,64.16666666666664, \
#                   40.666666666666664,34.5,30.33333333333337,21.666666666666682,29.666666666666707,86.83333333333341,60.99999999999998, \
#                   38.333333333333336,34.666666666666664,30.66666666666671,21.166666666666686,30.000000000000043} # The simulation time in s
# *.scenario = ${SS="initHeight-180_usi-10_mcs-3_uavspeed-6", "initHeight-180_usi-10_mcs-4_uavspeed-6", \
#                   "initHeight-180_usi-10_mcs-5_uavspeed-6", "initHeight-180_usi-10_mcs-6_uavspeed-6", \
#                   "initHeight-180_usi-10_mcs-7_uavspeed-6", "initHeight-180_usi-20_mcs-1_uavspeed-6", \
#                   "initHeight-180_usi-20_mcs-2_uavspeed-6", "initHeight-180_usi-20_mcs-3_uavspeed-6", \
#                   "initHeight-180_usi-20_mcs-4_uavspeed-6", "initHeight-180_usi-20_mcs-5_uavspeed-6", \
#                   "initHeight-180_usi-20_mcs-6_uavspeed-6", "initHeight-180_usi-20_mcs-7_uavspeed-6", \
#                   "initHeight-180_usi-66.7_mcs-1_uavspeed-6", "initHeight-180_usi-66.7_mcs-2_uavspeed-6", \
#                   "initHeight-180_usi-66.7_mcs-3_uavspeed-6", "initHeight-180_usi-66.7_mcs-4_uavspeed-6", \
#                   "initHeight-180_usi-66.7_mcs-5_uavspeed-6", "initHeight-180_usi-66.7_mcs-6_uavspeed-6", \
#                   "initHeight-180_usi-66.7_mcs-7_uavspeed-6", "initHeight-180_usi-100_mcs-1_uavspeed-6", \
#                   "initHeight-180_usi-100_mcs-2_uavspeed-6", "initHeight-180_usi-100_mcs-3_uavspeed-6", \
#                   "initHeight-180_usi-100_mcs-4_uavspeed-6", "initHeight-180_usi-100_mcs-5_uavspeed-6", \
#                   "initHeight-180_usi-100_mcs-6_uavspeed-6", "initHeight-180_usi-100_mcs-7_uavspeed-6" ! SIM}
*.simTime = ${SIM=91.00000000000023,37.83333333333335,22.166666666666682,19.499999999999993,22.66666666666667, \
                  59.833333333333265,44.3333333333333,40.166666666666664,26.166666666666693,24.0,25.666666666666693, \
                  90.16666666666677,71.00000000000004,43.99999999999997,39.66666666666666,33.50000000000002,23.000000000000007, \
                  31.833333333333368,95.00000000000013,72.83333333333341,44.666666666666636,39.49999999999998,33.33333333333336, \
                  22.833333333333343,32.33333333333337} # The simulation time in s
*.scenario = ${SS="initHeight-180_usi-10_mcs-3_uavspeed-6", "initHeight-180_usi-10_mcs-4_uavspeed-6", \
                  "initHeight-180_usi-10_mcs-5_uavspeed-6", "initHeight-180_usi-10_mcs-6_uavspeed-6", \
                  "initHeight-180_usi-10_mcs-7_uavspeed-6", \
                  "initHeight-180_usi-20_mcs-2_uavspeed-6", "initHeight-180_usi-20_mcs-3_uavspeed-6", \
                  "initHeight-180_usi-20_mcs-4_uavspeed-6", "initHeight-180_usi-20_mcs-5_uavspeed-6", \
                  "initHeight-180_usi-20_mcs-6_uavspeed-6", "initHeight-180_usi-20_mcs-7_uavspeed-6", \
                  "initHeight-180_usi-66.7_mcs-1_uavspeed-6", "initHeight-180_usi-66.7_mcs-2_uavspeed-6", \
                  "initHeight-180_usi-66.7_mcs-3_uavspeed-6", "initHeight-180_usi-66.7_mcs-4_uavspeed-6", \
                  "initHeight-180_usi-66.7_mcs-5_uavspeed-6", "initHeight-180_usi-66.7_mcs-6_uavspeed-6", \
                  "initHeight-180_usi-66.7_mcs-7_uavspeed-6", "initHeight-180_usi-100_mcs-1_uavspeed-6", \
                  "initHeight-180_usi-100_mcs-2_uavspeed-6", "initHeight-180_usi-100_mcs-3_uavspeed-6", \
                  "initHeight-180_usi-100_mcs-4_uavspeed-6", "initHeight-180_usi-100_mcs-5_uavspeed-6", \
                  "initHeight-180_usi-100_mcs-6_uavspeed-6", "initHeight-180_usi-100_mcs-7_uavspeed-6" ! SIM}

.csvFilePath = ${CSV="/home/clow0003/Reuben_ws/FANET_Dataset/height_adaptation_results/nn_calibrated_specificity_99/" + ${SS}}
*.scenarioManager.script = xmldoc("/home/clow0003/Reuben_ws/scenario_scripts_height_adaptation/scenario_scripts_1m_calibrated_4_specificity_99/" + ${SS} + "_scenario_script.xml") # Scenario Manager for MDP
*.bonnMovement = ${BM="/home/clow0003/Reuben_ws/bonn_motion_height_adaptation/bonn_motion_1m_calibrated_4_specificity_99/" + ${SS}  + ".movements"}

seed-set = ${SEED=0..199}

# -------------- For micro-sim ---------------------
sim-time-limit = ${SIM}s + 1s # Based on test case (plus 1 sec is extra buffer)
# To avoid file name too long issue
output-scalar-file = "${resultdir}/${configname}-${runnumber}.sca"  # use just the run number in the file name
output-vector-file = "${resultdir}/${configname}-${runnumber}.vec"  # use just the run number in the file name
eventlog-file = "${resultdir}/${configname}-${runnumber}.elog" # use just the run number in the file name
snapshot-file = "${resultdir}/${configname}-${runnumber}.sna" # use just the run number in the file name

# ----------- Mobility ---------- #
# GW-node mobility
*.gatewayNode.mobility.typename = "BonnMotionMobility"
*.gatewayNode.mobility.traceFile = ${BM}
*.gatewayNode.mobility.is3D = true
*.gatewayNode.mobility.nodeId = 0

# UAV member(s) mobility
*.adhocNode[*].mobility.typename = "AttachedMobility"
*.adhocNode[*].mobility.mobilityModule = "^.^.gatewayNode.mobility"
*.adhocNode[*].mobility.offsetX = ${R}m * cos(parentIndex() * (6.283185 / ${N}))
*.adhocNode[*].mobility.offsetY = ${R}m * sin(parentIndex() * (6.283185 / ${N}))
*.adhocNode[*].mobility.offsetZ = 0m
*.adhocNode[*].mobility.initFromDisplayString = false

# GCS mobility
**.GCS.mobility.typename = "StationaryMobility"
**.GCS.mobility.initialX = ${GX}m
**.GCS.mobility.initialY = ${GY}m
**.GCS.mobility.initialZ = 0m
**.GCS.mobility.initFromDisplayString = false

# Bounding box constraint
**.constraintAreaMinX = -100m
**.constraintAreaMinY = -100m
**.constraintAreaMinZ = 0m
**.constraintAreaMaxX = 1000m
**.constraintAreaMaxY = 1000m
**.constraintAreaMaxZ = 500m

#**.initFromDisplayString = false

# ---------------- Network Layer --------------------#
*.gatewayNode.ipv4.arp.typename = "GlobalArp"
*.GCS.ipv4.arp.typename = "GlobalArp"
*.adhocNode[*].ipv4.arp.typename = "GlobalArp"
# ---------------- Setting up routes and IP ------------------ #
*.configurator.config = xmldoc("fanet_routes.xml")
*.configurator.addStaticRoutes = false
*.configurator.dumpConfig = "routes_dump.xml"
*.configurator.dumpRoutes = false

# ----------- Setting up physical layer and channel ---------- #
# Radio
**.wlan[0].typename = "Ieee80211Interface"
**.wlan[0].radio.typename = "Ieee80211ScalarRadio"

# 802.11n
**.wlan[0].opMode = "n(mixed-2.4Ghz)"
**.numAntennas = 1
**.bandwidth = 20MHz
**.centerFrequency = 2.4GHz
**.wlan[*].mac.*.rateControl.typename = "CustomRateControl" # Use custom rate control so that MCS can be set by scenario scripts
**.wlan[*].mac.*.rateControl.initialRate = ${BR}Mbps # Will be set by scenario script. Just to fill it up

# Channel modelling 
#**.wlan[0].radio.transmitter.power = 100mW 
*.GCS.wlan[0].radio.transmitter.power = 100mW # 20 dBm
*.gatewayNode.wlan[0].radio.transmitter.power = 100mW # 20 dBm
*.adhocNode[*].wlan[0].radio.transmitter.power = 100mW  # 20 dBm
**.wlan[0].radio.receiver.sensitivity = -90dBm
#**.wlan[0].radio.receiver.energyDetection = -90dBm
*.radioMedium.backgroundNoise.power = -86dBm # -107dBm, -86dBm
**.pathLoss.typename = "LognormalRicianFading"
**.pathLoss.a = 0.1
**.pathLoss.b = 0.00075
**.pathLoss.c = 8
**.pathLoss.alpha_min = 2
**.pathLoss.alpha_max = 2.75
**.pathLoss.sigma_a = 11.1852
**.pathLoss.sigma_b = 0.06
**.pathLoss.K_min = 1.4922 # (In dB) For suburban in 2.4GHz
**.pathLoss.K_max = 12.2272  # (In dB) For suburban in 2.4GHz
**.propagation.typename = "ConstantSpeedPropagation"

# Set fragmentation threshold to allow no-fragmentation of video packets
**.mac.dcf.originatorMacDataService.fragmentationPolicy.fragmentationThreshold = 1574B

# -----------  Application ---------- #
# Flow 1 Application (Broadcast CNC messages to UAV nodes) 
# GCS
*.GCS.ipv4.ip.directBroadcastInterfaces = "wlan0"
*.GCS.numApps = 3 # 2
*.GCS.app[0].typename = "UdpGCSCsvApp"
*.GCS.app[0].localPort = 5000
*.GCS.app[0].destPort = 5000
*.GCS.app[0].packetName = "CNCData"
*.GCS.app[0].destAddresses = "adhocNode[0] adhocNode[1] adhocNode[2] gatewayNode" # Just to fill it up, not actually used in this mode
*.GCS.app[0].numMemberUAVs = ${N}
*.GCS.app[0].sendInterval = ${EGSI}ms
*.GCS.app[0].startTime = uniform(0ms, 1ms)
*.GCS.app[0].stopTime = ${SIM}s 
*.GCS.app[0].numPacketRecord = ${NPR}
*.GCS.app[0].pcapCsvFileName = ${DLPCSV}
*.GCS.app[0].seed = ${SEED} # For shuffling PCAP data
*.GCS.app[0].timeToLive = 255
*.GCS.app[1].typename = "UdpSinkRecordCsv"
*.GCS.app[1].localPort = 5001
*.GCS.app[1].receiveBroadcast = true
*.GCS.app[2].typename = "UdpSinkRecordCsv"
*.GCS.app[2].localPort = 5002
*.GCS.app[2].receiveBroadcast = true

# Gateway
*.gatewayNode.numApps = 3 # 2
*.gatewayNode.app[0].typename = "UdpSinkRecordCsv"
*.gatewayNode.app[0].localPort = 5000
*.gatewayNode.app[0].receiveBroadcast = true
*.gatewayNode.app[1].typename = "UdpBasicCsvApp"
*.gatewayNode.app[1].localPort = 5001
*.gatewayNode.app[1].destPort = 5001
*.gatewayNode.app[1].packetName = "GatewayData"
*.gatewayNode.app[1].destAddresses = "GCS"
*.gatewayNode.app[1].timeToLive = 255
*.gatewayNode.app[1].sendInterval = ${EUSI}ms
*.gatewayNode.app[1].startTime = uniform(1ms, 2ms)
*.gatewayNode.app[1].stopTime = ${SIM}s 
*.gatewayNode.app[1].numPacketRecord = ${NPR} # NPR set to -1 to indicate record all packets sent # int(ceil(${NPR} / (${N}+1)))
*.gatewayNode.app[1].pcapCsvFileName = ${ULPCSV}
*.gatewayNode.app[1].seed = ${SEED} # For shuffling PCAP data
*.gatewayNode.app[1].dontFragment = true
*.gatewayNode.app[2].typename = "UdpBasicAppRecordCsv"
*.gatewayNode.app[2].localPort = 5002
*.gatewayNode.app[2].destPort = 5002
*.gatewayNode.app[2].messageLength = ${VPS}bytes
*.gatewayNode.app[2].sendInterval = ${VPS}ms * 8 * 0.001 / ${VBR}
*.gatewayNode.app[2].packetName = "GatewayVideo" # Important to name it this
*.gatewayNode.app[2].destAddresses = "GCS"
*.gatewayNode.app[2].timeToLive = 255
*.gatewayNode.app[2].startTime = uniform(1ms, 10ms)
*.gatewayNode.app[2].stopTime = ${SIM}s 
*.gatewayNode.app[2].numPacketRecord = ${NPR}
*.gatewayNode.app[2].dontFragment = true

# UAVs
*.adhocNode[*].numApps = 2
*.adhocNode[*].app[0].typename = "UdpSinkRecordCsv"
*.adhocNode[*].app[0].localPort = 5000
*.adhocNode[*].app[0].receiveBroadcast = true
*.adhocNode[*].app[1].typename = "UdpBasicCsvApp"
*.adhocNode[*].app[1].localPort = 5001
*.adhocNode[*].app[1].destPort = 5001
*.adhocNode[*].app[1].packetName = "UAVData_" + string(parentIndex())
*.adhocNode[*].app[1].destAddresses = "GCS"
*.adhocNode[*].app[1].timeToLive = 255
*.adhocNode[*].app[1].sendInterval = ${EUSI}ms
*.adhocNode[*].app[1].startTime = uniform(2ms + ms(parentIndex()), 3ms + ms(parentIndex()))
*.adhocNode[*].app[1].stopTime = ${SIM}s  
*.adhocNode[*].app[1].numPacketRecord = ${NPR} # NPR set to -1 to indicate record all packets sent # int(ceil(${NPR} / (${N}+1)))
*.adhocNode[*].app[1].pcapCsvFileName = ${ULPCSV}
*.adhocNode[*].app[1].seed = ${SEED} # For shuffling PCAP data

# ----------- Recording Data ------------#
#**.result-recording-modes = -vector
#**.app[*].throughput.result-recording-modes = +vector
#*.gatewayNode.wlan[0].radio.minSnir.result-recording-modes = +vector
#*.radioMedium.recordCommunicationLog = true

# Storing to CSV File
# Application level monitoring

*.GCS.wlan[0].radio.receiver.csvFilePath = ${CSV}
*.GCS.wlan[0].radio.receiver.csvFileName = "Run-" + string(${SEED}) + "_GCS-Wlan.csv"
*.GCS.app[*].csvFilePath = ${CSV}
*.GCS.app[0].csvFileNameTx = "Run-" + string(${SEED}) + "_GCS-Tx.csv"
*.GCS.app[0].csvFileNameRx = "Run-" + string(${SEED}) + "_GCS-Rx.csv"
*.GCS.app[1].csvFileName = "Run-" + string(${SEED}) + "_GCS-Rx.csv"
*.GCS.app[2].csvFileName = "Run-" + string(${SEED}) + "_GCS-Video-Rx.csv"

*.gatewayNode.wlan[0].radio.receiver.csvFilePath = ${CSV}
*.gatewayNode.wlan[0].radio.receiver.csvFileName = "Run-" + string(${SEED}) + "_GW-Wlan.csv"
*.gatewayNode.app[*].csvFilePath = ${CSV}
*.gatewayNode.app[0].csvFileName = "Run-" + string(${SEED}) + "_GW-Rx.csv"
*.gatewayNode.app[1].csvFileName = "Run-" + string(${SEED}) + "_GW-Tx.csv"
*.gatewayNode.app[2].csvFileName = "Run-" + string(${SEED}) + "_GW-Video-Tx.csv"

*.adhocNode[*].wlan[0].radio.receiver.csvFilePath = ${CSV}
*.adhocNode[*].wlan[0].radio.receiver.csvFileName = "Run-" + string(${SEED}) + "_UAV-" + string(ancestorIndex(3)) + "-Wlan.csv"
*.adhocNode[*].app[*].csvFilePath = ${CSV}
*.adhocNode[*].app[0].csvFileName = "Run-" + string(${SEED}) + "_UAV-" + string(parentIndex()) + "-Rx.csv"
*.adhocNode[*].app[1].csvFileName = "Run-" + string(${SEED}) + "_UAV-" + string(parentIndex()) + "-Tx.csv"


# ----------- Setting up PCAP Recording ---------- #
#*.gatewayNode.numPcapRecorders = 3
#*.gatewayNode.pcapRecorder[2].pcapFile = ${PCAP}
##*.GCS.pcapRecorder[*].packetFilter = "*CNCData" # NOT WORKING
#**.crcMode = "computed"
#**.fcsMode = "computed"

# ----------- Setting up Visualization ---------- #
*.visualizer.physicalLinkVisualizer.displayLinks = true
*.visualizer.mobilityVisualizer[*].displayVelocities = false
*.visualizer.mobilityVisualizer[*].displayMovementTrails = false
*.visualizer.interfaceTableVisualizer[*].displayInterfaceTables = true
*.visualizer.physicalLinkVisualizer[*].displayLinks = true
*.visualizer.physicalLinkVisualizer[*].packetFilter = "CNCData UAVData* GatewayData"

#*.GCS.wlan[0].radio.displayCommunicationRange = true
#*.gatewayNode.wlan[0].radio.displayCommunicationRange = true
#*.adhocNode*.wlan[0].radio.displayInterferenceRange = true
**.wlan[0].radio.displayCommunicationRange = true
*.visualizer.dataLinkVisualizer[*].displayLinks = true
*.visualizer.dataLinkVisualizer[*].packetFilter = "CNCData UAVData* GatewayData"
*.visualizer.networkRouteVisualizer[*].displayRoutes = true
#*.visualizer.*.routingTableVisualizer[*].displayRoutingTables = true
#*.visualizer.*.routingTableVisualizer[*].destinationFilter = "*"
