'''
Date: 4/12/2024
Desc: To process the raw data from simulation runs of rebroadcasting scheme to count the occurence of n consecutive packet failures.
    Only sim runs where switching occured will be processed
'''

import pandas as pd # for data manipulation 
import numpy as np
# import matplotlib.pyplot as plt # for drawing graphs
import os, sys, glob, math
import time
from multiprocessing.pool import Pool
from itertools import repeat

def compile_rx_data(file_list):
    '''
    Function to compile RX data as list of DFs from the CSV files generated by each micro-simulation
    Input: file_list - List of simulation files belonging to a certain scenario (micro-sim)
    Output: list of Rx DFs
    '''
    # Specify dtypes to save memory
    rx_df_dtypes = {"RxTime": np.float64, "TxTime": np.float32,	"Packet_Name": "str", "Bytes": np.uint16, "RSSI": 'str', "U2G_SINR": np.float32, "U2U_SINR": np.float32, 
                    "U2G_BER": np.float32, "U2U_BER": np.float32, "Src_Addr": 'category', "Dest_Addr": 'category', "Hop_Count": np.uint8, "Delay": np.float32, 
                    "Queueing_Time": np.float32, "Backoff_Time": np.float32, "U2G_Distance": np.float32, "Retry_Count": np.uint8}

    # Let's get the GCS dfs ===============================================================
    gcs_rx_file = [file for file in file_list if ('_GCS-Rx.csv' in file)]
    if len(gcs_rx_file) > 0:
        gcs_rx_df = pd.read_csv(gcs_rx_file[0], dtype=rx_df_dtypes)
    else:
        print("GCS RX File Missing")
        print(file_list[0])

    # Let's get the GW dfs ===============================================================
    gw_rx_file = [file for file in file_list if (('_GW-Rx' in file))]
    if len(gw_rx_file) > 0:
        gw_rx_df = pd.read_csv(gw_rx_file[0], dtype=rx_df_dtypes)
    else:
        print("GW RX File Missing")
        print(file_list[0])

    # Let's get the UAVs dfs ===============================================================
    uavs_rx_df_list = []
    uav_rx_files = [file for file in file_list if (('_UAV-' in file) and ('-Rx' in file))]
    uav_rx_files.sort()
    if len(uav_rx_files) > 0:
        for uav_rx_file in uav_rx_files:
            uavs_rx_df_list.append(pd.read_csv(uav_rx_file, dtype=rx_df_dtypes))
    else:
        print("UAV RX File(s) Missing")
        print(file_list[0])

    rx_df_list = [gcs_rx_df, gw_rx_df] + uavs_rx_df_list

    return rx_df_list
def process_scenario_manual(scenario_path, save_path, switch_time_path, num_processes, dl_delay_threshold, ul_delay_threshold, run_num, n_period):
    '''
    delay_threshold: Delay Constraint for reliability calculation
    run_num: Max run number to consider
    n_period: Number of periods (sending intervals) to consider for consecutive packet losses
    '''
    scenario = scenario_path.split("/")[-1]
    print(scenario)
    
    # UNCOMMENT BELOW TO ONLY PROCESS SCENARIOS WHERE THE SAVE_PATH DIR IS NOT YET CREATED
    # if os.path.isdir(os.path.join(save_path, scenario)):
    #     print("Skipping processed scenario")
    #     return

    scenario_params = scenario.split('_')
    usi = float([x for x in scenario_params if "UAVSendingInterval" in x][0].split('-')[-1])
    uav_speed = float([x for x in scenario_params if "UAVSpeed" in x][0].split('-')[-1])
    height = float([x for x in scenario_params if "Height" in x][0].split('-')[-1])
    bitrate = float([x for x in scenario_params if "BitRate" in x][0].split('-')[-1])
    distance = float([x for x in scenario_params if "Distance" in x][0].split('-')[-1])
    assert uav_speed > 0, "Mode slideWindow assumes UAVs are moving linearly with speed uav_speed, which cannot be 0"

    metric_list = []
    max_time = distance / uav_speed # This is the max time to consider for packet receptions (let's not include the buffer time)
    switch_time_df = pd.read_csv(switch_time_path)
    switch_time_df = switch_time_df.loc[(switch_time_df["Height"]==height)&(switch_time_df["USI"]==usi)&(switch_time_df["Bit_Rate"]==bitrate)&(switch_time_df["UAV_Speed"]==uav_speed)]
    switch_time_df = switch_time_df.loc[switch_time_df["Run"]<=run_num]
    # switch_time_df.dropna(subset=["Switch_Time"], inplace=True) # Deprecated since 23/12/2024
    # Get rows where not all switch times are nan
    run_df = switch_time_df[["Run"]]
    switch_time_df = switch_time_df[["GCS_Switch_Time", "GW_Switch_Time", "UAV_0_Switch_Time", "UAV_2_Switch_Time", "UAV_3_Switch_Time", "UAV_4_Switch_Time",
                                     "UAV_5_Switch_Time", "UAV_6_Switch_Time", "UAV_7_Switch_Time"]]
    switch_time_df_notna = switch_time_df.loc[~switch_time_df.isnull().all(axis=1)]
    run_df = run_df.loc[~switch_time_df.isnull().all(axis=1)]
    if not switch_time_df_notna.empty: # If the scenario has no runs where switching occured, no need to process
        # switch_time = switch_time_df["Switch_Time"].values # Deprecated since 23/12/2024
        switch_time_df_notna['Min_Switch_Time'] = switch_time_df_notna[["GCS_Switch_Time", "GW_Switch_Time", "UAV_0_Switch_Time", "UAV_2_Switch_Time", "UAV_3_Switch_Time", "UAV_4_Switch_Time",
                                                            "UAV_5_Switch_Time", "UAV_6_Switch_Time", "UAV_7_Switch_Time"]].min(axis=1)
        switch_time = switch_time_df_notna["Min_Switch_Time"].values
        run_number = run_df["Run"].values # Get the run_number based on switch time (we only process runs where a switch to mitigation occured)
        with Pool(num_processes) as pool:
            for result in pool.starmap(process_run_manual, zip(run_number, repeat(scenario_path), repeat(dl_delay_threshold), repeat(ul_delay_threshold), switch_time, repeat(max_time), repeat(n_period), repeat(usi))):
                
                metric_list.append({"Run": result[0], "GCS_Cons_Fail": result[1], "UAV_0_Cons_Fail": result[2], "UAV_1_Cons_Fail": result[3], "UAV_2_Cons_Fail": result[4], 
                                    "UAV_3_Cons_Fail": result[5], "UAV_4_Cons_Fail": result[6], "UAV_5_Cons_Fail": result[7], "UAV_6_Cons_Fail": result[2], "UAV_7_Cons_Fail": result[8]})
    
    # Create save file directory if not created
    if not os.path.isdir(os.path.join(save_path, scenario)):
        os.mkdir(os.path.join(save_path, scenario))
    
    # Save metrics of each run to file
    if len(metric_list) > 0:
        metric_df = pd.DataFrame(metric_list)
    else:
        metric_df = pd.DataFrame(columns=['Run','GCS_Cons_Fail','UAV_0_Cons_Fail','UAV_1_Cons_Fail','UAV_2_Cons_Fail','UAV_3_Cons_Fail',
                                          'UAV_4_Cons_Fail','UAV_5_Cons_Fail','UAV_6_Cons_Fail','UAV_7_Cons_Fail'])
    metric_df.to_csv(os.path.join(save_path, scenario, "Cons_Fail_{}_period.csv".format(n_period)), index=False)
    
    return

def process_run_manual(run_number, scenario_path, dl_delay_threshold, ul_delay_threshold, switch_time, max_time, n_period, usi):
    '''
    For manual mode (switch time must be provided, assumes all link switch same time)
    Searches for gaps of length n_secs between packet receptions for each link.
    If such gaps are identified, it will return 1 for the link.
    NOTE: Provide file_path such that the files for a particular run number can be identified using glob.glob(file_path.format(run_number))
          Max time should be the time the Tx app stops
          usi must be given in ms
    '''
    file_path = os.path.join(scenario_path, "Run-{}_*.csv")
    run_files = glob.glob(file_path.format(run_number)) # Get list of csv files belonging to this scenario

    rx_df_list = compile_rx_data(run_files)

    # Find presence of n consecutive packet loss in GCS Rx
    gcs_cons_fail = 0 # 0 indicates no n consecutive packet failure, 1 means yes
    gcs_rx_df = rx_df_list[0]
    gcs_rx_df["Delay"] = gcs_rx_df['RxTime']-gcs_rx_df['TxTime'] # Calc delay of packets received
    gcs_reliable_rx_df = gcs_rx_df.loc[['Waypoint' in name for name in gcs_rx_df.Packet_Name] & (gcs_rx_df["Delay"]<=ul_delay_threshold)]
    n_secs = n_period * 20 / 1000 # GCS sending interval is 20 ms for DJI Spark
    if (max_time - switch_time) >= n_secs: # If at least n_secs elapsed after switch time
        gcs_reliable_rx_df = gcs_reliable_rx_df.loc[gcs_reliable_rx_df["TxTime"]>=switch_time]
        # Append switch time and front and max time at back, so that can check if there is a gap >= n_sec between first packet after switch with swicth time, and between last packet and max time
        rx_time_series = pd.concat([pd.Series([switch_time]), gcs_reliable_rx_df["RxTime"], pd.Series([max_time])])
        rx_time_diff = rx_time_series.diff().dropna()
        if not rx_time_diff.empty:
            if rx_time_diff.gt(n_secs + ul_delay_threshold).any():
                gcs_cons_fail = 1
    else: # In this case, set to nan
        gcs_cons_fail = np.nan

    # Find presence of n consecutive packet loss in UAVs' Rx DFs     
    uavs_cons_fail = np.zeros(len(rx_df_list)-1)
    n_secs = n_period * usi / 1000 # GCS sending interval is 20 ms for DJI Spark
    for i in range(1,len(rx_df_list)):
        uav_rx_df = rx_df_list[i]
        uav_rx_df["Delay"] = uav_rx_df['RxTime']-uav_rx_df['TxTime']
        uav_reliable_rx_df = uav_rx_df.loc[['Waypoint' in name for name in uav_rx_df.Packet_Name] & (uav_rx_df["Delay"]<=dl_delay_threshold)]  
        if (max_time - switch_time) >= n_secs: # If at least n_secs elapsed after switch time
            uav_reliable_rx_df = uav_reliable_rx_df.loc[uav_reliable_rx_df["TxTime"]>=switch_time]
            # Append switch time and front and max time at back, so that can check if there is a gap >= n_sec between first packet after switch with swicth time, and between last packet and max time
            rx_time_series = pd.concat([pd.Series([switch_time]), uav_reliable_rx_df["RxTime"], pd.Series([max_time])])
            rx_time_diff = rx_time_series.diff().dropna()
            if not rx_time_diff.empty:
                # if rx_time_diff.gt(n_secs + dl_delay_threshold).any():
                if rx_time_diff.gt(n_secs).any():
                    uavs_cons_fail[i-1] = 1
        else: # In this case, set to nan
            uavs_cons_fail[i-1] = np.nan
        
    return (run_number, gcs_cons_fail, *uavs_cons_fail)

def process_scenario_waypoint(scenario_path, save_path, switch_time_path, num_processes, dl_delay_threshold, ul_delay_threshold, run_num, n_period):
    '''
    delay_threshold: Delay Constraint for reliability calculation
    run_num: Max run number to consider
    n_period: Number of periods (sending intervals) to consider for consecutive packet losses
    '''
    scenario = scenario_path.split("/")[-1]
    print(scenario)
    
    # UNCOMMENT BELOW TO ONLY PROCESS SCENARIOS WHERE THE SAVE_PATH DIR IS NOT YET CREATED
    # if os.path.isdir(os.path.join(save_path, scenario)):
    #     print("Skipping processed scenario")
    #     return

    scenario_params = scenario.split('_')
    usi = float([x for x in scenario_params if "UAVSendingInterval" in x][0].split('-')[-1])
    uav_speed = float([x for x in scenario_params if "UAVSpeed" in x][0].split('-')[-1])
    height = float([x for x in scenario_params if "Height" in x][0].split('-')[-1])
    bitrate = float([x for x in scenario_params if "BitRate" in x][0].split('-')[-1])
    distance = float([x for x in scenario_params if "Distance" in x][0].split('-')[-1])
    assert uav_speed > 0, "Mode slideWindow assumes UAVs are moving linearly with speed uav_speed, which cannot be 0"

    metric_list = []
    max_time = distance / uav_speed # This is the max time to consider for packet receptions (let's not include the buffer time)
    switch_time_df = pd.read_csv(switch_time_path)
    switch_time_df = switch_time_df.loc[(switch_time_df["Height"]==height)&(switch_time_df["USI"]==usi)&(switch_time_df["Bit_Rate"]==bitrate)&(switch_time_df["UAV_Speed"]==uav_speed)]
    switch_time_df = switch_time_df.loc[switch_time_df["Run"]<=run_num]
    # switch_time_df.dropna(subset=["Switch_Time"], inplace=True) # Deprecated since 23/12/2024
    # Get rows where not all switch times are nan
    run_df = switch_time_df[["Run"]]
    switch_time_df = switch_time_df[["GCS_Switch_Time", "GW_Switch_Time", "UAV_0_Switch_Time", "UAV_2_Switch_Time", "UAV_3_Switch_Time", "UAV_4_Switch_Time",
                                     "UAV_5_Switch_Time", "UAV_6_Switch_Time", "UAV_7_Switch_Time"]]
    run_df = run_df.loc[~switch_time_df.isnull().all(axis=1)]
    if not run_df.empty: # If the scenario has no runs where switching occured, no need to process
        run_number = run_df["Run"].values # Get the run_number based on switch time (we only process runs where a switch to mitigation occured)
        with Pool(num_processes) as pool:
            for result in pool.starmap(process_run_waypoint, zip(run_number, repeat(scenario_path), repeat(dl_delay_threshold), repeat(ul_delay_threshold), repeat(max_time), repeat(n_period))):
                
                metric_list.append({"Run": result[0], "GCS_Cons_Fail": result[1], "UAV_0_Cons_Fail": result[2], "UAV_1_Cons_Fail": result[3], "UAV_2_Cons_Fail": result[4], 
                                    "UAV_3_Cons_Fail": result[5], "UAV_4_Cons_Fail": result[6], "UAV_5_Cons_Fail": result[7], "UAV_6_Cons_Fail": result[2], "UAV_7_Cons_Fail": result[8]})
    
    # Create save file directory if not created
    if not os.path.isdir(os.path.join(save_path, scenario)):
        os.mkdir(os.path.join(save_path, scenario))
    
    # Save metrics of each run to file
    if len(metric_list) > 0:
        metric_df = pd.DataFrame(metric_list)
    else:
        metric_df = pd.DataFrame(columns=['Run','GCS_Cons_Fail','UAV_0_Cons_Fail','UAV_1_Cons_Fail','UAV_2_Cons_Fail','UAV_3_Cons_Fail',
                                          'UAV_4_Cons_Fail','UAV_5_Cons_Fail','UAV_6_Cons_Fail','UAV_7_Cons_Fail'])
    metric_df.to_csv(os.path.join(save_path, scenario, "Cons_Fail_{}_period.csv".format(n_period)), index=False)
    
    return

def process_run_waypoint(run_number, scenario_path, dl_delay_threshold, ul_delay_threshold, max_time, n_period):
    '''
    For waypoint mode (which will have Run-{}_Switch_Time.csv)
    Searches for gaps of length n_secs between packet receptions for each link.
    If such gaps are identified, it will return 1 for the link.
    NOTE: Provide file_path such that the files for a particular run number can be identified using glob.glob(file_path.format(run_number))
          Max time should be the time the Tx app stops
    '''
    file_path = os.path.join(scenario_path, "Run-{}_*.csv")
    run_files = glob.glob(file_path.format(run_number)) # Get list of csv files belonging to this scenario

    rx_df_list = compile_rx_data(run_files)
    switch_time_df = pd.read_csv(os.path.join(scenario_path, "Run-{}_Switch_Time.csv".format(run_number)))
    
    # Since sending interval in waypoint mode is 1 sec, n_secs = n_period 
    n_secs = n_period

    # Find presence of n consecutive packet loss in GCS Rx
    gcs_cons_fail = 0 # 0 indicates no n consecutive packet failure, 1 means yes
    gcs_rx_df = rx_df_list[0]
    gcs_rx_df["Delay"] = gcs_rx_df['RxTime']-gcs_rx_df['TxTime'] # Calc delay of packets received
    gcs_reliable_rx_df = gcs_rx_df.loc[['Waypoint' in name for name in gcs_rx_df.Packet_Name] & (gcs_rx_df["Delay"]<=ul_delay_threshold)]
    # try:
    switch_time_ = switch_time_df.loc[[True if "GCS" in x else False for x in switch_time_df["Module"]]]
    if not switch_time_.empty:
        switch_time = switch_time_["Switch_Time"].values[0]
        if (max_time - switch_time) >= n_secs: # If at least n_secs elapsed after switch time
            gcs_reliable_rx_df = gcs_reliable_rx_df.loc[gcs_reliable_rx_df["TxTime"]>=switch_time]
            # Append switch time and front and max time at back, so that can check if there is a gap >= n_sec between first packet after switch with swicth time, and between last packet and max time
            rx_time_series = pd.concat([pd.Series([switch_time]), gcs_reliable_rx_df["RxTime"], pd.Series([max_time])])
            rx_time_diff = rx_time_series.diff().dropna()
            if not rx_time_diff.empty:
                # if rx_time_diff.gt(n_secs + ul_delay_threshold).any():
                if rx_time_diff.gt(n_secs).any():
                    gcs_cons_fail = 1
        else: # In this case, set to nan
            gcs_cons_fail = np.nan
    else:
        gcs_cons_fail = np.nan

    # Find presence of n consecutive packet loss in UAVs' Rx DFs     
    uavs_cons_fail = np.zeros(len(rx_df_list)-1)
    for i in range(1,len(rx_df_list)):
        uav_rx_df = rx_df_list[i]
        uav_rx_df["Delay"] = uav_rx_df['RxTime']-uav_rx_df['TxTime']
        uav_reliable_rx_df = uav_rx_df.loc[['Waypoint' in name for name in uav_rx_df.Packet_Name] & (uav_rx_df["Delay"]<=dl_delay_threshold)]
        # try:
        if i == 1: # This is the gateway
            switch_time_ = switch_time_df.loc[[True if "gatewayNode" in x else False for x in switch_time_df["Module"]]]
        else:
            switch_time_ = switch_time_df.loc[[True if "adhocNode[{}]".format(i-2) in x else False for x in switch_time_df["Module"]]]
        
        if not switch_time_.empty:
            switch_time = switch_time_["Switch_Time"].values[0]
            if (max_time - switch_time) >= n_secs: # If at least n_secs elapsed after switch time
                uav_reliable_rx_df = uav_reliable_rx_df.loc[uav_reliable_rx_df["TxTime"]>=switch_time]
                # Append switch time and front and max time at back, so that can check if there is a gap >= n_sec between first packet after switch with swicth time, and between last packet and max time
                rx_time_series = pd.concat([pd.Series([switch_time]), uav_reliable_rx_df["RxTime"], pd.Series([max_time])])
                rx_time_diff = rx_time_series.diff().dropna()
                if not rx_time_diff.empty:
                    # if rx_time_diff.gt(n_secs + dl_delay_threshold).any():
                    if rx_time_diff.gt(n_secs).any():
                        uavs_cons_fail[i-1] = 1
            else: # In this case, set to nan
                uavs_cons_fail[i-1] = np.nan
        else:
            uavs_cons_fail[i-1] = np.nan

    return (run_number, gcs_cons_fail, *uavs_cons_fail)
    
def process_run_waypoint_time_window(run_number, scenario_path, dl_delay_threshold, ul_delay_threshold, max_time, n_secs):
    '''
    Searches for occurence of time windows (length n_sec) in which no packets are received for each link.
    NOTE: Provide file_path such that the files for a particular run number can be identified using glob.glob(file_path.format(run_number))
    '''
    file_path = os.path.join(scenario_path, "Run-{}_*.csv")
    run_files = glob.glob(file_path.format(run_number)) # Get list of csv files belonging to this scenario

    rx_df_list = compile_rx_data(run_files)
    switch_time_df = pd.read_csv(os.path.join(scenario_path, "Run-{}_Switch_Time.csv".format(run_number)))
    
    # uavs_rx_df = pd.concat(rx_df_list[1:len(rx_df_list)], ignore_index=True) # Includes GW Rx DF and all UAVs Rx DFs

    # Find presence of n consecutive packet loss in GCS Rx
    gcs_cons_fail = 0 # 0 indicates no n consecutive packet failure, 1 means yes
    gcs_rx_df = rx_df_list[0]
    gcs_rx_df["Delay"] = gcs_rx_df['RxTime']-gcs_rx_df['TxTime'] # Calc delay of packets received
    gcs_reliable_rx_df = gcs_rx_df.loc[['Waypoint' in name for name in gcs_rx_df.Packet_Name] & (gcs_rx_df["Delay"]<=ul_delay_threshold)]
    try:
        switch_time = switch_time_df.loc[[True if "GCS" in x else False for x in switch_time_df["Module"]]]["Switch_Time"].values[0]
        if (max_time - switch_time) >= n_secs: # If at least n_secs elapsed after switch time
            # Use time window of size n_secs and stride of 1 sec
            for i in range(math.floor((max_time - switch_time - n_secs) + 1)):
                # Check for any reliably received waypoint packets within the time window spanning (i) to (i+n_secs)
                rx_df_in_range = gcs_reliable_rx_df.loc[(gcs_reliable_rx_df["RxTime"] >= (switch_time+i)) & (gcs_reliable_rx_df["RxTime"] < (switch_time+i+n_secs))] # Get reliable rcvd packets within time window
                if rx_df_in_range.empty:
                    gcs_cons_fail = 1
                    break
        else: # In this case, set to nan
            gcs_cons_fail = np.nan
    except Exception as e:
        # print(run_number)
        # print(e)
        gcs_cons_fail = np.nan

    # Find presence of n consecutive packet loss in UAVs' Rx DFs     
    uavs_cons_fail = np.zeros(len(rx_df_list)-1)
    for i in range(1,len(rx_df_list)):
        uav_rx_df = rx_df_list[i]
        uav_rx_df["Delay"] = uav_rx_df['RxTime']-uav_rx_df['TxTime']
        uav_reliable_rx_df = uav_rx_df.loc[['Waypoint' in name for name in uav_rx_df.Packet_Name] & (uav_rx_df["Delay"]<=dl_delay_threshold)]
        try:
            if i == 1: # This is the gateway
                switch_time = switch_time_df.loc[[True if "gatewayNode" in x else False for x in switch_time_df["Module"]]]["Switch_Time"].values[0]
            else:
                switch_time = switch_time_df.loc[[True if "adhocNode[{}]".format(i-2) in x else False for x in switch_time_df["Module"]]]["Switch_Time"].values[0]
            if (max_time - switch_time) >= n_secs: # If at least n_secs elapsed after switch time
                # Use time window of size n_secs and stride of 1 sec
                for j in range(math.floor((max_time - switch_time - n_secs) + 1)):
                    # Check for any reliably received waypoint packets within the time window spanning (j) to (j+n_secs)
                    rx_df_in_range = uav_reliable_rx_df.loc[(uav_reliable_rx_df["RxTime"] >= (switch_time + j)) & (uav_reliable_rx_df["RxTime"] < (switch_time + j + n_secs))] # Get reliable rcvd packets within time window
                    if rx_df_in_range.empty:
                        uavs_cons_fail[i-1] = 1
                        break
            else: # In this case, set to nan
                uavs_cons_fail[i-1] = np.nan
        except Exception as e:
            # print(run_number)
            # print(e)
            uavs_cons_fail[i-1] = np.nan
        
    return (run_number, gcs_cons_fail, *uavs_cons_fail)

if __name__ == "__main__":
    pd.options.mode.chained_assignment = None
    # sim_root_paths, save_paths, and switch_time_paths need to correspond to each other
    # WAYPOINT MODE
    sim_root_paths = ["/media/research-student/DataDrive/FANET_Dataset/DJISpark_Obj3_Retransmission_Datasets/G+U_Fixed100_UAV_Interference_Dmax100/uav_scenario_0",
                      "/media/research-student/DataDrive/FANET_Dataset/DJISpark_Obj3_Retransmission_Datasets/G+U_Fixed100_UAV_Interference_Dmax100/uav_scenario_1",
                      "/media/research-student/DataDrive/FANET_Dataset/DJISpark_Obj3_Retransmission_Datasets/G+U_Fixed100_UAV_Interference_Dmax100/uav_scenario_2",
                      "/media/research-student/DataDrive/FANET_Dataset/DJISpark_Obj3_Retransmission_Datasets/G+U_Fixed100_MANET_Interference_Dmax100/manet_scenario_1",
                      "/media/research-student/DataDrive/FANET_Dataset/DJISpark_Obj3_Retransmission_Datasets/G+U_Fixed100_MANET_Interference_Dmax100/manet_scenario_a",
                      "/media/research-student/DataDrive/FANET_Dataset/DJISpark_Obj3_Retransmission_Datasets/G+U_Fixed100_MANET_Interference_Dmax100/manet_scenario_2"]
    save_paths = ["/media/research-student/DataDrive/FANET_Dataset/DJISpark_Obj3_Retransmission_Datasets/G+U_Fixed100_UAV_Interference_Dmax100/uav_scenario_0_processed",
                      "/media/research-student/DataDrive/FANET_Dataset/DJISpark_Obj3_Retransmission_Datasets/G+U_Fixed100_UAV_Interference_Dmax100/uav_scenario_1_processed",
                      "/media/research-student/DataDrive/FANET_Dataset/DJISpark_Obj3_Retransmission_Datasets/G+U_Fixed100_UAV_Interference_Dmax100/uav_scenario_2_processed",
                      "/media/research-student/DataDrive/FANET_Dataset/DJISpark_Obj3_Retransmission_Datasets/G+U_Fixed100_MANET_Interference_Dmax100/manet_scenario_1_processed",
                      "/media/research-student/DataDrive/FANET_Dataset/DJISpark_Obj3_Retransmission_Datasets/G+U_Fixed100_MANET_Interference_Dmax100/manet_scenario_a_processed",
                      "/media/research-student/DataDrive/FANET_Dataset/DJISpark_Obj3_Retransmission_Datasets/G+U_Fixed100_MANET_Interference_Dmax100/manet_scenario_2_processed"]
    switch_time_paths = ["/home/research-student/omnet-fanet/data-processing-scripts/journal_3_scripts/obj3_scenario_script_new/uav_scenario_0/Switch_Details.csv",
                         "/home/research-student/omnet-fanet/data-processing-scripts/journal_3_scripts/obj3_scenario_script_new/uav_scenario_1/Switch_Details.csv",
                         "/home/research-student/omnet-fanet/data-processing-scripts/journal_3_scripts/obj3_scenario_script_new/uav_scenario_2/Switch_Details.csv",
                         "/home/research-student/omnet-fanet/data-processing-scripts/journal_3_scripts/obj3_scenario_script_new/manet_scenario_1/Switch_Details.csv",
                         "/home/research-student/omnet-fanet/data-processing-scripts/journal_3_scripts/obj3_scenario_script_new/manet_scenario_a/Switch_Details.csv",
                         "/home/research-student/omnet-fanet/data-processing-scripts/journal_3_scripts/obj3_scenario_script_new/manet_scenario_2/Switch_Details.csv"]
    # Delay constraints for waypoint mode
    dl_delay_threshold = 1
    ul_delay_threshold = 1
    RUN_NUM = 99 # Max run number to consider, note it starts at 0
    N_PERIOD = 3 # Number of period to consider for consecutive packet losses (one period corresponding to sending interval)
    MODE = "waypoint"

    # # MANUAL CONTROL
    # sim_root_paths = ["/home/rlim0005/FANET_Dataset/DJISpark_Obj3_Retransmission_Datasets/Manual_UAV_Interference_Dmax100/uav_scenario_0", 
    #                   "/home/rlim0005/FANET_Dataset/DJISpark_Obj3_Retransmission_Datasets/Manual_UAV_Interference_Dmax100/uav_scenario_1", 
    #                   "/home/rlim0005/FANET_Dataset/DJISpark_Obj3_Retransmission_Datasets/Manual_UAV_Interference_Dmax100/uav_scenario_2", 
    #                   "/home/rlim0005/FANET_Dataset/DJISpark_Obj3_Retransmission_Datasets/Manual_MANET_Interference_Dmax100/manet_scenario_1",
    #                   "/home/rlim0005/FANET_Dataset/DJISpark_Obj3_Retransmission_Datasets/Manual_MANET_Interference_Dmax100/manet_scenario_a",
    #                   "/home/rlim0005/FANET_Dataset/DJISpark_Obj3_Retransmission_Datasets/Manual_MANET_Interference_Dmax100/manet_scenario_2"]
    # save_paths = ["/home/rlim0005/FANET_Dataset/DJISpark_Obj3_Retransmission_Datasets/Manual_UAV_Interference_Dmax100/uav_scenario_0_processed",
    #               "/home/rlim0005/FANET_Dataset/DJISpark_Obj3_Retransmission_Datasets/Manual_UAV_Interference_Dmax100/uav_scenario_1_processed",
    #               "/home/rlim0005/FANET_Dataset/DJISpark_Obj3_Retransmission_Datasets/Manual_UAV_Interference_Dmax100/uav_scenario_2_processed",
    #               "/home/rlim0005/FANET_Dataset/DJISpark_Obj3_Retransmission_Datasets/Manual_MANET_Interference_Dmax100/manet_scenario_1_processed",
    #               "/home/rlim0005/FANET_Dataset/DJISpark_Obj3_Retransmission_Datasets/Manual_MANET_Interference_Dmax100/manet_scenario_a_processed",
    #               "/home/rlim0005/FANET_Dataset/DJISpark_Obj3_Retransmission_Datasets/Manual_MANET_Interference_Dmax100/manet_scenario_2_processed"]
    # switch_time_paths = ["/home/rlim0005/obj3_scenario_script_new/uav_scenario_0/Switch_Details.csv",
    #                      "/home/rlim0005/obj3_scenario_script_new/uav_scenario_1/Switch_Details.csv",
    #                      "/home/rlim0005/obj3_scenario_script_new/uav_scenario_2/Switch_Details.csv",
    #                      "/home/rlim0005/obj3_scenario_script_new/manet_scenario_1/Switch_Details.csv",
    #                      "/home/rlim0005/obj3_scenario_script_new/manet_scenario_a/Switch_Details.csv",
    #                      "/home/rlim0005/obj3_scenario_script_new/manet_scenario_2/Switch_Details.csv"]
    # # Delay constraints for waypoint mode
    # dl_delay_threshold = 0.04
    # ul_delay_threshold = 0.04
    # RUN_NUM = 499 # Max run number to consider, note it starts at 0
    # N_PERIOD = 2 # Number of period to consider for consecutive packet losses (one period corresponding to sending interval)
    # MODE = "manual"

    num_processes = 64
    
    for sim_root_path, save_path, switch_time_path in zip(sim_root_paths, save_paths, switch_time_paths):
        # Create save file directory if not created
        if not os.path.isdir(os.path.join(save_path)):
            os.mkdir(os.path.join(save_path))    

        scenario_list = [f.path for f in os.scandir(sim_root_path) if f.is_dir()] # Get list of "unique" scenarios
        # For each scenario, extract the UL and DL raw data
        for scenario_path in scenario_list:
            if MODE == "waypoint":
                process_scenario_waypoint(scenario_path, save_path, switch_time_path, num_processes, dl_delay_threshold, ul_delay_threshold, RUN_NUM, N_PERIOD)
            elif MODE == "manual":
                process_scenario_manual(scenario_path, save_path, switch_time_path, num_processes, dl_delay_threshold, ul_delay_threshold, RUN_NUM, N_PERIOD)
