# Date: 16/06/2024
#Desc: Simulation for communication reliability of UAV swarm
#      To get maximum horizontal distance for maintenance scheme
[General]

[Config Hovering_Swarm]
description = To generate FANET communication reliability dataset with traffic from PCAP CSV
network = fanet_adhoc_hosts_pcap
#record-eventlog = true

## --------------------- Reliability Prediction TRAINING DATASET ----------------------------------
*.numPacketsRecord = ${NPR=100000} # NPR set to -1 to indicate record all packets sent
*.numHosts = ${N=7}
*.swarmDistance = ${GX=0..500 step 10} # X coord of GCS, in m
*.gcsX = ${GXGCS=0} # X coord of GCS, in m
*.gcsY = ${GY=0} # Y coord of GCS, in m
*.swarmHeight = ${Z=70, 100, 130, 160, 190, 220, 250, 280} # Doing it one height at a time due to space constraint
*.uavRadius = ${R=5}
*.modulation = ${MCS="BPSK", "QPSK", "QPSK", "QAM-16", "QAM-16", "QAM-64", "QAM-64", "QAM-64"} #"QAM-64", "QAM-16", "QPSK", "BPSK"
*.MCSBitrate = ${BR=6.5, 13, 19.5, 26, 39, 52, 58.5, 65 ! MCS} # 6.5, 13, 19.5, 26, 39, 52, 58.5, 65 Mbps
# --------------------------------------------------------------
*.uavSendingInterval = ${EUSI=66.7, 100} # In ms
*.gcsSendingInterval = ${EGSI=20} # In ms
*.videoBitRate = ${VBR=2} # In Mbps
*.videoPacketSize = ${VPS=1450} # In bytes (with header of 64 bytes)
*.videoSendingInterval = ${VSI=($VPS) * 8 * 0.001 / ($VBR)} # In ms
.dlPcapCsvFilePath = ${DLPCSV="/home/research-student/omnet-fanet/uav_traffic_csv/djispark_dl.csv"} 
.ulPcapCsvFilePath = ${ULPCSV="/home/research-student/omnet-fanet/uav_traffic_csv/djispark_ul.csv"} 
.csvFilePath = ${CSV="/media/research-student/KingstonSSD/FANET_Dataset/Dataset_NP100000_DJISpark/max_hdist_batch_2/" + \
					"NumMember-" + string(${N}) + "_BitRate-" + string(${BR}) + "_Height-" + string(${Z}) + \
					"_Distance-" + string(${GX}-${GXGCS}) + "_Modulation-" + ${MCS} + "_UAVSendingInterval-" + string(${EUSI})}

# -------------- For micro-sim ---------------------
*.maxUSI = ${MAXUSI=max(${EUSI}, ${EGSI})} # Max between UAV and GCS sending interval
*.simTime = ${SIMTIME=max(${NPR}s / (1000 / ${MAXUSI} * (${N}+1)) + 10s, ${NPR}s / (1000 / (${VSI})) + 10s)} # For micro-sim, determine the sim time from number of packets and sending rate (plus 10 is extra buffer)
sim-time-limit = ${SIMTIME} 

#seed-set = ${SEED=1..ceil($NP / ((($HDR/$USP)-1)*10))} # For measured throughput, it is based on slide window and stride size to hit NP measurements
# To avoid file name too long issue
output-scalar-file = "${resultdir}/${configname}-${runnumber}.sca"  # use just the run number in the file name
output-vector-file = "${resultdir}/${configname}-${runnumber}.vec"  # use just the run number in the file name
eventlog-file = "${resultdir}/${configname}-${runnumber}.elog" # use just the run number in the file name
snapshot-file = "${resultdir}/${configname}-${runnumber}.sna" # use just the run number in the file name
**.result-recording-modes = - # Let's see if this stops recording of stats to .sca and .vec files

# ----------- Mobility ---------- #
# GW-node mobility
*.gatewayNode.mobility.typename = "StationaryMobility"
*.gatewayNode.mobility.initialY = ${GY}m
*.gatewayNode.mobility.initialX = ${GX}m
*.gatewayNode.mobility.initialZ = ${Z}m
*.gatewayNode.mobility.initFromDisplayString = false

# UAV member(s) mobility
*.adhocNode[*].mobility.typename = "StationaryMobility"
*.adhocNode[*].mobility.initialX = ${GX}m + ${R}m * cos(parentIndex() * (6.283185 / ${N}))
*.adhocNode[*].mobility.initialY = ${GY}m + ${R}m * sin(parentIndex() * (6.283185 / ${N}))
*.adhocNode[*].mobility.initialZ = ${Z}m
*.adhocNode[*].mobility.initFromDisplayString = false

# GCS mobility
**.GCS.mobility.typename = "StationaryMobility"
**.GCS.mobility.initialX = ${GXGCS}m
**.GCS.mobility.initialY = ${GY}m
**.GCS.mobility.initialZ = 0m
**.GCS.mobility.initFromDisplayString = false

# Bounding box constraint
**.constraintAreaMinX = -100m
**.constraintAreaMinY = -100m
**.constraintAreaMinZ = -100m
**.constraintAreaMaxX = 2200m
**.constraintAreaMaxY = 1000m
**.constraintAreaMaxZ = 500m

#**.initFromDisplayString = false

# ---------------- Network Layer --------------------#
*.gatewayNode.ipv4.arp.typename = "GlobalArp"
*.GCS.ipv4.arp.typename = "GlobalArp"
*.adhocNode[*].ipv4.arp.typename = "GlobalArp"
# ---------------- Setting up routes and IP ------------------ #
*.configurator.config = xmldoc("fanet_routes.xml")
*.configurator.addStaticRoutes = false
*.configurator.dumpConfig = "routes_dump.xml"
*.configurator.dumpRoutes = true

# ----------- Setting up physical layer and channel ---------- #
# Radio
**.wlan[0].typename = "Ieee80211Interface"
**.wlan[0].radio.typename = "Ieee80211ScalarRadio"

# 802.11n
**.wlan[0].opMode = "n(mixed-2.4Ghz)"
**.numAntennas = 1
**.bandwidth = 20MHz
**.centerFrequency = 2.4GHz
**.wlan[*].bitrate = ${BR}Mbps
**.wlan[*].radio.transmitter.modulation = ${MCS} #"QAM-64", "QAM-16", "QPSK", "BPSK"

# Channel modelling 
#**.wlan[0].radio.transmitter.power = 100mW 
*.GCS.wlan[0].radio.transmitter.power = 100mW # 20 dBm
*.gatewayNode.wlan[0].radio.transmitter.power = 100mW # 20 dBm
*.adhocNode[*].wlan[0].radio.transmitter.power = 100mW  # 20 dBm
**.wlan[0].radio.receiver.sensitivity = -90dBm
#**.wlan[0].radio.receiver.energyDetection = -90dBm
*.radioMedium.backgroundNoise.power = -86dBm # -107dBm, -86dBm
**.pathLoss.typename = "LognormalRicianFading"
**.pathLoss.a = 0.1
**.pathLoss.b = 0.00075
**.pathLoss.c = 8
**.pathLoss.alpha_min = 2
**.pathLoss.alpha_max = 2.75
**.pathLoss.sigma_a = 11.1852
**.pathLoss.sigma_b = 0.06
**.pathLoss.K_min = 1.4922 # (In dB) For suburban in 2.4GHz
**.pathLoss.K_max = 12.2272  # (In dB) For suburban in 2.4GHz
**.propagation.typename = "ConstantSpeedPropagation"

# Set fragmentation threshold to allow no-fragmentation of video packets
**.mac.dcf.originatorMacDataService.fragmentationPolicy.fragmentationThreshold = 1574B

# -----------  Application ---------- #
# Flow 1 Application (Broadcast CNC messages to UAV nodes) 
# GCS
*.GCS.ipv4.ip.directBroadcastInterfaces = "wlan0"
*.GCS.numApps = 3 # 2
*.GCS.app[0].typename = "UdpGCSCsvApp"
*.GCS.app[0].localPort = 5000
*.GCS.app[0].destPort = 5000
*.GCS.app[0].packetName = "CNCData"
*.GCS.app[0].destAddresses = "adhocNode[0] adhocNode[1] adhocNode[2] gatewayNode" # Just to fill it up, not actually used in this mode
*.GCS.app[0].numMemberUAVs = ${N}
*.GCS.app[0].sendInterval = ${EGSI}ms
*.GCS.app[0].startTime = uniform(0ms, 1ms)
*.GCS.app[0].stopTime = ${SIMTIME}
*.GCS.app[0].numPacketRecord = ${NPR}
*.GCS.app[0].pcapCsvFileName = ${DLPCSV}
*.GCS.app[0].timeToLive = 255
*.GCS.app[1].typename = "UdpSinkRecordCsv"
*.GCS.app[1].localPort = 5001
*.GCS.app[1].receiveBroadcast = true
*.GCS.app[2].typename = "UdpSinkRecordCsv"
*.GCS.app[2].localPort = 5002
*.GCS.app[2].receiveBroadcast = true

# Gateway
*.gatewayNode.numApps = 3 # 2
*.gatewayNode.app[0].typename = "UdpSinkRecordCsv"
*.gatewayNode.app[0].localPort = 5000
*.gatewayNode.app[0].receiveBroadcast = true
*.gatewayNode.app[1].typename = "UdpBasicCsvApp"
*.gatewayNode.app[1].localPort = 5001
*.gatewayNode.app[1].destPort = 5001
*.gatewayNode.app[1].packetName = "GatewayData"
*.gatewayNode.app[1].destAddresses = "GCS"
*.gatewayNode.app[1].timeToLive = 255
*.gatewayNode.app[1].sendInterval = ${EUSI}ms
*.gatewayNode.app[1].startTime = uniform(1ms, 2ms)
*.gatewayNode.app[1].stopTime = ${SIMTIME}
*.gatewayNode.app[1].numPacketRecord = int(ceil(${NPR} / (${N}+1))) # NPR set to -1 to indicate record all packets sent # int(ceil(${NPR} / (${N}+1)))
*.gatewayNode.app[1].pcapCsvFileName = ${ULPCSV}
*.gatewayNode.app[1].dontFragment = true
*.gatewayNode.app[2].typename = "UdpBasicAppRecordCsv"
*.gatewayNode.app[2].localPort = 5002
*.gatewayNode.app[2].destPort = 5002
*.gatewayNode.app[2].messageLength = ${VPS}bytes
*.gatewayNode.app[2].sendInterval = ${VPS}ms * 8 * 0.001 / ${VBR}
*.gatewayNode.app[2].packetName = "GatewayVideo" # Important to name it this
*.gatewayNode.app[2].destAddresses = "GCS"
*.gatewayNode.app[2].timeToLive = 255
*.gatewayNode.app[2].startTime = uniform(1ms, 10ms)
*.gatewayNode.app[2].stopTime = ${SIMTIME}
*.gatewayNode.app[2].numPacketRecord = ${NPR}
*.gatewayNode.app[2].dontFragment = true

# UAVs
*.adhocNode[*].numApps = 2
*.adhocNode[*].app[0].typename = "UdpSinkRecordCsv"
*.adhocNode[*].app[0].localPort = 5000
*.adhocNode[*].app[0].receiveBroadcast = true
*.adhocNode[*].app[1].typename = "UdpBasicCsvApp"
*.adhocNode[*].app[1].localPort = 5001
*.adhocNode[*].app[1].destPort = 5001
*.adhocNode[*].app[1].packetName = "UAVData_" + string(parentIndex())
*.adhocNode[*].app[1].destAddresses = "GCS"
*.adhocNode[*].app[1].timeToLive = 255
*.adhocNode[*].app[1].sendInterval = ${EUSI}ms
*.adhocNode[*].app[1].startTime = uniform(2ms + ms(parentIndex()), 3ms + ms(parentIndex()))
*.adhocNode[*].app[1].stopTime = ${SIMTIME}
*.adhocNode[*].app[1].numPacketRecord = int(ceil(${NPR} / (${N}+1))) # NPR set to -1 to indicate record all packets sent # int(ceil(${NPR} / (${N}+1)))
*.adhocNode[*].app[1].pcapCsvFileName = ${ULPCSV}

# ----------- Recording Data ------------#
#**.result-recording-modes = -vector
#**.app[*].throughput.result-recording-modes = +vector
#*.gatewayNode.wlan[0].radio.minSnir.result-recording-modes = +vector
#*.radioMedium.recordCommunicationLog = true

# Storing to CSV File
# Application level monitoring

*.GCS.wlan[0].radio.receiver.csvFilePath = ${CSV}
*.GCS.wlan[0].radio.receiver.csvFileName = "GCS-Wlan.csv"
*.GCS.app[*].csvFilePath = ${CSV}
*.GCS.app[0].csvFileNameTx = "GCS-Tx.csv"
*.GCS.app[0].csvFileNameRx = "_"
*.GCS.app[1].csvFileName = "GCS-Rx.csv"
*.GCS.app[2].csvFileName = "GCS-Video-Rx.csv"

*.gatewayNode.wlan[0].radio.receiver.csvFilePath = ${CSV}
*.gatewayNode.wlan[0].radio.receiver.csvFileName = "GW-Wlan.csv"
*.gatewayNode.app[*].csvFilePath = ${CSV}
*.gatewayNode.app[0].csvFileName = "GW-Rx.csv"
*.gatewayNode.app[1].csvFileName = "GW-Tx.csv"
*.gatewayNode.app[2].csvFileName = "GW-Video-Tx.csv"

*.adhocNode[*].wlan[0].radio.receiver.csvFilePath = ${CSV}
*.adhocNode[*].wlan[0].radio.receiver.csvFileName = "UAV-" + string(ancestorIndex(3)) + "-Wlan.csv"
*.adhocNode[*].app[*].csvFilePath = ${CSV}
*.adhocNode[*].app[0].csvFileName = "UAV-" + string(parentIndex()) + "-Rx.csv"
*.adhocNode[*].app[1].csvFileName = "UAV-" + string(parentIndex()) + "-Tx.csv"

# ----------- Setting up Visualization ---------- #
*.visualizer.physicalLinkVisualizer.displayLinks = true
*.visualizer.mobilityVisualizer[*].displayVelocities = false
*.visualizer.mobilityVisualizer[*].displayMovementTrails = false
*.visualizer.interfaceTableVisualizer[*].displayInterfaceTables = true
*.visualizer.physicalLinkVisualizer[*].displayLinks = true
*.visualizer.physicalLinkVisualizer[*].packetFilter = "CNCData UAVData* GatewayData"

#*.GCS.wlan[0].radio.displayCommunicationRange = true
#*.gatewayNode.wlan[0].radio.displayCommunicationRange = true
#*.adhocNode*.wlan[0].radio.displayInterferenceRange = true
**.wlan[0].radio.displayCommunicationRange = true
*.visualizer.dataLinkVisualizer[*].displayLinks = true
*.visualizer.dataLinkVisualizer[*].packetFilter = "CNCData UAVData* GatewayData"
*.visualizer.networkRouteVisualizer[*].displayRoutes = true
#*.visualizer.*.routingTableVisualizer[*].displayRoutingTables = true
#*.visualizer.*.routingTableVisualizer[*].destinationFilter = "*"

