'''
Date Modified: 10/11/2024
Desc: Pandas data processing of FANET dataset with multiprocessing.
      FOR RELIABILITY OF WAYPOINT MODE ONLY GCS BROADCAST (No Rebroadcasting or Retransmissions)
      Reads RX CSV file and calculates throughput for each time step
      Uses sliding window approach
      Modified: to processing DL GCS-2-UAV throughput individually per UAV, rather than combining everything
      Modified: For evaluating broadcast scenarios
      Modified: For saving results for each run separately
      Modified: Modified fanet_data_preprocessing_throughput_rebroadcast_07012024.py for high number of runs rather than high number of scenarios.
                Multiprocessing is done to compile the results from multiple runs in each scenario, rather than work on multiple scenarios in parallel
      Modified: To limit results up to a certain horizontal distance for waypoint mode.
      Modified from fanet_data_preprocessing_reliability_waypoint_only_broadcast_25052024.py to exclude packets sent before switching time.
      Modified from fanet_data_preprocessing_mitigation_waypoint_only_19092024.py to use new kind of switch time CSV (from gamma thresholding)
      Modified to use new switch time file format where switch time of all UAVs and GCS are recorded
'''

import pandas as pd # for data manipulation 
import numpy as np
# import matplotlib.pyplot as plt # for drawing graphs
import os, sys, glob, math
import time
from multiprocessing.pool import Pool
from itertools import repeat
from tqdm import tqdm
from scipy import special

def compile_micro_sim_data_v2(file_list):
    '''
    Function to compile data from the CSV files generated by each micro-simulation
    Update: To specifically return the rx_df, tx_df, mon_df and pd_df in lists, so that specific dfs can be accessed (instead of aggregating UAV dfs)
    Input: file_list - List of simulation files belonging to a certain scenario (micro-sim)
            video - flag to indicate whether to compile video data
    Output: concatenates the raw data to UL and DL dataframes
    '''
    # Specify dtypes to save memory
    tx_df_dtypes = {"TxTime": np.float32, "Packet_Name": "category", "Packet_Seq": np.uint32, "Bytes": np.uint16, "Dest_Addr": 'category'}
    rx_df_dtypes = {"RxTime": np.float64, "TxTime": np.float32,	"Packet_Name": "str", "Bytes": np.uint16, "RSSI": 'str', "U2G_SINR": np.float32, "U2U_SINR": np.float32, 
                    "U2G_BER": np.float32, "U2U_BER": np.float32, "Src_Addr": 'category', "Dest_Addr": 'category', "Hop_Count": np.uint8, "Delay": np.float32, 
                    "Queueing_Time": np.float32, "Backoff_Time": np.float32, "U2G_Distance": np.float32, "Retry_Count": np.uint8}
    pd_df_dtypes = {"RxTime": np.float64, "TxTime": np.float32,	"Packet_Name": "str", "Bytes": np.uint16, "RSSI": 'str', "U2G_SINR": np.float32, "U2U_SINR": np.float32, 
                    "U2G_BER": np.float32, "U2U_BER": np.float32, "Delay": np.float32, "Queueing_Time": np.float32, "Backoff_Time": np.float32, "U2G_Distance": np.float16,
                    "Has_Bit_Error": np.uint8, "Packet_Drop_Reason": 'category'}
    br_df_dtypes = {"TxTime": np.float32, "Packet_Name": "str", "Bytes": np.uint16, "Dest_Addr": 'category'}

    # Let's get the GCS dfs ===============================================================
    gcs_rx_file = [file for file in file_list if ('_GCS-Rx.csv' in file)]
    gcs_tx_file = [file for file in file_list if ('_GCS-Tx.csv' in file)]
    gcs_mon_file = [file for file in file_list if ('_GCS-Wlan.csv' in file)]
    gcs_pd_file = [file for file in file_list if ('_GCS-PacketDrop.csv' in file)]
    if len(gcs_rx_file) > 0:
        gcs_rx_df = pd.read_csv(gcs_rx_file[0], dtype=rx_df_dtypes)
    else:
        print("GCS RX File Missing")
        print(file_list[0])
    if len(gcs_tx_file) > 0:
        gcs_tx_df = pd.read_csv(gcs_tx_file[0], dtype=tx_df_dtypes)
    else:
        print("GCS TX File Missing")
        print(file_list[0])
    if len(gcs_pd_file) > 0:
        gcs_pd_df = pd.read_csv(gcs_pd_file[0], dtype=pd_df_dtypes)
    else:
        print("GCS PD File Missing")
        print(file_list[0])
    
    if len(gcs_mon_file) > 0:
        gcs_mon_df = pd.read_csv(gcs_mon_file[0]) # Mon file is optional
        gcs_mon_df["Addr"] = "192.168.0.1"
    else: 
        gcs_mon_df = None

    # Let's get the GW dfs ===============================================================
    gw_rx_file = [file for file in file_list if (('_GW-Rx' in file))]
    gw_tx_file = [file for file in file_list if (('_GW-Tx' in file))]
    gw_mon_file = [file for file in file_list if (('_GW-Wlan' in file))]
    gw_pd_file = [file for file in file_list if (('_GW-PacketDrop' in file))]
    if len(gw_rx_file) > 0:
        gw_rx_df = pd.read_csv(gw_rx_file[0], dtype=rx_df_dtypes)
    else:
        print("GW RX File Missing")
        print(file_list[0])
    if len(gw_tx_file) > 0:
        gw_tx_df = pd.read_csv(gw_tx_file[0], dtype=tx_df_dtypes)
    else:
        print("GW TX File Missing")
        print(file_list[0])
    if len(gw_pd_file) > 0:
        gw_pd_df = pd.read_csv(gw_pd_file[0], dtype=pd_df_dtypes)
    else:
        print("GW PD File Missing")
        print(file_list[0])
    if len(gw_mon_file) > 0:
        gw_mon_df = pd.read_csv(gw_mon_file[0]) # Mon file is optional
        gw_mon_df["Addr"] = "192.168.0.2"
    else:
        gw_mon_df = None

    # Let's get the UAVs dfs ===============================================================
    uavs_rx_df_list = []
    uavs_tx_df_list = []
    uavs_mon_df_list = []
    uavs_pd_df_list = []
    uavs_br_df_list = []
    uav_rx_files = [file for file in file_list if (('_UAV-' in file) and ('-Rx.csv' in file))]
    uav_tx_files = [file for file in file_list if (('_UAV-' in file) and ('-Tx.csv' in file))]
    uav_mon_files = [file for file in file_list if (('_UAV-' in file) and ('-Wlan.csv' in file))]
    uav_pd_files = [file for file in file_list if (('_UAV-' in file) and ('-PacketDrop.csv' in file))]
    uav_rx_files.sort()
    uav_tx_files.sort()
    uav_mon_files.sort()
    uav_pd_files.sort()
    if len(uav_rx_files) > 0:
        for uav_rx_file in uav_rx_files:
            uavs_rx_df_list.append(pd.read_csv(uav_rx_file, dtype=rx_df_dtypes))
    else:
        print("UAV RX File(s) Missing")
        print(file_list[0])
    if len(uav_tx_files) > 0:
        for uav_tx_file in uav_tx_files:
            uavs_tx_df_list.append(pd.read_csv(uav_tx_file, dtype=tx_df_dtypes))
    else:
        print("UAV TX File(s) Missing")
        print(file_list[0])
    if len(uav_pd_files) > 0:
        for uav_pd_file in uav_pd_files:
            uavs_pd_df_list.append(pd.read_csv(uav_pd_file, dtype=pd_df_dtypes))
    else:
        print("UAV PD File(s) Missing")
        print(file_list[0])
    if len(uav_mon_files) > 0: # UAV mon files are optional now
        uav_member_index = 3
        for uav_mon_file in uav_mon_files:
            uav_mon_df = pd.read_csv(uav_mon_file)
            uav_mon_df["Addr"] = "192.168.0." + str(uav_member_index)
            uavs_mon_df_list.append(uav_mon_df)
            uav_member_index += 1
    else:
        uavs_mon_df_list = []

    rx_df_list = [gcs_rx_df, gw_rx_df] + uavs_rx_df_list
    tx_df_list = [gcs_tx_df, gw_tx_df] + uavs_tx_df_list
    pd_df_list = [gcs_pd_df, gw_pd_df] + uavs_pd_df_list
    mon_df_list = [gcs_mon_df, gw_mon_df] + uavs_mon_df_list
    
    return rx_df_list, tx_df_list, pd_df_list, mon_df_list

def count_packet_states(rx_df, pd_df, delay_threshold):
    """
    Desc: Count the number of reliable, delay excd, incr rcvd and q overflow packets for each micro-sim
    ASSUMPTION: The total number of packets in uavs_rx_df and gcs_pd_df makes up the total number of packets transmitted in downlink (gcs_tx_df)
                RETRY_LIMIT_REACHED is due to incorrectly received in downlink
    """
    # Make sure that the packets recorded as retry limit reach and queue overflow in pd_df are not in fact received in rx_df
    rx_packets = rx_df["Packet_Name"].values
    pd_df = pd_df.loc[~pd_df["Packet_Name"].isin(rx_packets)]

    delay = rx_df['RxTime']-rx_df['TxTime']
    num_reliable = np.sum(np.where(delay > delay_threshold , 0, 1))
    num_delay_excd = len(rx_df) - num_reliable
    pkt_drop_counts = pd_df["Packet_Drop_Reason"].value_counts()
    if len(pkt_drop_counts) > 2:
        print("ALERT: More than 2 packet drop reason found!")
    
    if "RETRY_LIMIT_REACHED" in pkt_drop_counts:
        num_incr_rcvd = pkt_drop_counts["RETRY_LIMIT_REACHED"]
    else:
        num_incr_rcvd = 0
    if "QUEUE_OVERFLOW" in pkt_drop_counts:
        num_queue_overflow = pkt_drop_counts["QUEUE_OVERFLOW"]
    else:
        num_queue_overflow = 0

    return num_reliable, num_delay_excd, num_incr_rcvd, num_queue_overflow

def process_scenario_broadcast(scenario_path, save_path, switch_time_path, num_processes, 
                        dl_delay_threshold, ul_delay_threshold, run_num):
    '''
    Modified: To process all different runs of each sccenario (for measured throughput while UAV moving)
    Modified: For broadcast scenarios
    dl indicates Downlink. Likewise for ul (Uplink) and vid (Video)
    slot_size: the length of the slot size in seconds
    stride: The sliding window will slide by "stride" seconds
    delay_threshold: Delay Constraint for reliability calculation
    run_num: Max run number to consider
    '''
    scenario = scenario_path.split("/")[-1]
    print(scenario)
    
    # UNCOMMENT BELOW TO ONLY PROCESS SCENARIOS WHERE THE SAVE_PATH DIR IS NOT YET CREATED
    # if os.path.isdir(os.path.join(save_path, scenario)):
    #     print("Skipping processed scenario")
    #     return

    scenario_params = scenario.split('_')
    usi = float([x for x in scenario_params if "UAVSendingInterval" in x][0].split('-')[-1])
    uav_speed = float([x for x in scenario_params if "UAVSpeed" in x][0].split('-')[-1])
    height = float([x for x in scenario_params if "Height" in x][0].split('-')[-1])
    bitrate = float([x for x in scenario_params if "BitRate" in x][0].split('-')[-1])
    assert uav_speed > 0, "Mode slideWindow assumes UAVs are moving linearly with speed uav_speed, which cannot be 0"

    metric_list = []
    switch_time_df = pd.read_csv(switch_time_path)
    switch_time_df = switch_time_df.loc[(switch_time_df["Height"]==height)&(switch_time_df["USI"]==usi)&(switch_time_df["Bit_Rate"]==bitrate)&(switch_time_df["UAV_Speed"]==uav_speed)]
    switch_time_df = switch_time_df.loc[switch_time_df["Run"]<=run_num]
    # switch_time_df.dropna(subset=["Switch_Time"], inplace=True) # Deprecated since 23/12/2024
    # Get rows where not all switch times are nan
    run_df = switch_time_df[["Run"]]
    switch_time_df = switch_time_df[["GCS_Switch_Time", "GW_Switch_Time", "UAV_0_Switch_Time", "UAV_2_Switch_Time", "UAV_3_Switch_Time", "UAV_4_Switch_Time",
                                     "UAV_5_Switch_Time", "UAV_6_Switch_Time", "UAV_7_Switch_Time"]]
    switch_time_df_notna = switch_time_df.loc[~switch_time_df.isnull().all(axis=1)]
    run_df = run_df.loc[~switch_time_df.isnull().all(axis=1)]
    if not switch_time_df_notna.empty: # If the scenario has no runs where switching occured, no need to process
        # switch_time = switch_time_df["Switch_Time"].values # Deprecated since 23/12/2024
        switch_time_df_notna['Min_Switch_Time'] = switch_time_df_notna[["GCS_Switch_Time", "GW_Switch_Time", "UAV_0_Switch_Time", "UAV_2_Switch_Time", "UAV_3_Switch_Time", "UAV_4_Switch_Time",
                                                            "UAV_5_Switch_Time", "UAV_6_Switch_Time", "UAV_7_Switch_Time"]].min(axis=1)
        switch_time = switch_time_df_notna["Min_Switch_Time"].values
        run_number = run_df["Run"].values # Get the run_number based on switch time (we only process runs where a switch to mitigation occured)
        with Pool(num_processes) as pool:
            for result in pool.starmap(process_run, zip(run_number, switch_time, repeat(scenario_path),
                                                        repeat(dl_delay_threshold), repeat(ul_delay_threshold))):
                
                metric_list.append({"Run": result[0], "Num_Pkts_Reliable_UAV_0": result[1][0], "Num_Pkts_Reliable_UAV_1": result[1][1], "Num_Pkts_Reliable_UAV_2": result[1][2],
                                    "Num_Pkts_Reliable_UAV_3": result[1][3], "Num_Pkts_Reliable_UAV_4": result[1][4], "Num_Pkts_Reliable_UAV_5": result[1][5], "Num_Pkts_Reliable_UAV_6": result[1][6],
                                    "Num_Pkts_Reliable_UAV_7": result[1][7], "Num_Pkts_Reliable_UL": result[2], 
                                    "Reliability_UAV_0": result[3][0], "Reliability_UAV_1": result[3][1], "Reliability_UAV_2": result[3][2], "Reliability_UAV_3": result[3][3],
                                    "Reliability_UAV_4": result[3][4], "Reliability_UAV_5": result[3][5], "Reliability_UAV_6": result[3][6], "Reliability_UAV_7": result[3][7],
                                    "Total_Reliability_UL": result[4], 
                                    "Num_Delay_Excd_UAV_0": result[5][0], "Num_Delay_Excd_UAV_1": result[5][1], "Num_Delay_Excd_UAV_2": result[5][2], "Num_Delay_Excd_UAV_3": result[5][3],
                                    "Num_Delay_Excd_UAV_4": result[5][4], "Num_Delay_Excd_UAV_5": result[5][5], "Num_Delay_Excd_UAV_6": result[5][6], "Num_Delay_Excd_UAV_7": result[5][7], 
                                    "UL_Num_Delay_Excd": result[6], "UL_Num_Incr_Rcvd": result[7], "UL_Num_Queue_Overflow": result[8]})
    
    # Create save file directory if not created
    if not os.path.isdir(os.path.join(save_path, scenario)):
        os.mkdir(os.path.join(save_path, scenario))
    
    # Save metrics of each run to file
    if len(metric_list) > 0:
        metric_df = pd.DataFrame(metric_list)
    else:
        metric_df = pd.DataFrame(columns=["Run", "Num_Pkts_Reliable_UAV_0", "Num_Pkts_Reliable_UAV_1", "Num_Pkts_Reliable_UAV_2","Num_Pkts_Reliable_UAV_3", 
                                    "Num_Pkts_Reliable_UAV_4", "Num_Pkts_Reliable_UAV_5", "Num_Pkts_Reliable_UAV_6", "Num_Pkts_Reliable_UAV_7", "Num_Pkts_Reliable_UL", 
                                    "Reliability_UAV_0", "Reliability_UAV_1", "Reliability_UAV_2", "Reliability_UAV_3",
                                    "Reliability_UAV_4", "Reliability_UAV_5", "Reliability_UAV_6", "Reliability_UAV_7", "Total_Reliability_UL", 
                                    "Num_Delay_Excd_UAV_0", "Num_Delay_Excd_UAV_1", "Num_Delay_Excd_UAV_2", "Num_Delay_Excd_UAV_3",
                                    "Num_Delay_Excd_UAV_4", "Num_Delay_Excd_UAV_5", "Num_Delay_Excd_UAV_6", "Num_Delay_Excd_UAV_7", 
                                    "UL_Num_Delay_Excd", "UL_Num_Incr_Rcvd", "UL_Num_Queue_Overflow"])
    metric_df.to_csv(os.path.join(save_path, scenario, "Broadcast_Metrics.csv"), index=False)
    
    return
    
def process_run(run_number, switch_time, scenario_path, dl_delay_threshold, ul_delay_threshold):
    '''
    Provide file_path such that the files for a particular run number can be identified using glob.glob(file_path.format(run_number))
    '''
    file_path = os.path.join(scenario_path, "Run-{}_*.csv")
    run_files = glob.glob(file_path.format(run_number)) # Get list of csv files belonging to this scenario

    rx_df_list, tx_df_list, pd_df_list, mon_df_list = compile_micro_sim_data_v2(run_files)

    # Sort out which df is which
    gcs_rx_df = rx_df_list[0]
    gcs_tx_df = tx_df_list[0]
    gcs_pd_df = pd_df_list[0]
    # uavs_rx_df = pd.concat(rx_df_list[1:len(rx_df_list)], ignore_index=True) # Includes GW Rx DF and all UAVs Rx DFs
    uavs_tx_df = pd.concat(tx_df_list[1:len(tx_df_list)], ignore_index=True) # Includes GW Tx DF and all UAVs Tx DFs
    uavs_pd_df = pd.concat(pd_df_list[1:len(pd_df_list)], ignore_index=True)

    '''OLD Method of filtering by switch time'''
    # # Forward fill packet name in TX DFs, so that it is not nan for rows > 1
    # gcs_tx_df.ffill(inplace=True) # This is to forward fill the packet name
    # uavs_tx_df.ffill(inplace=True) # This is to forward fill the packet name
    # # Filter out packet sent before switch time
    # gcs_tx_df = gcs_tx_df.loc[gcs_tx_df["TxTime"] >= switch_time]
    # gcs_rx_df = gcs_rx_df.loc[gcs_rx_df["TxTime"] >= switch_time]
    # uavs_tx_df = uavs_tx_df.loc[uavs_tx_df["TxTime"] >= switch_time]
    # # Since gcs_pd_df and uavs_pd_df TxTime is always 0, reference the corresponding tx_df to filter packets
    # gcs_tx_df["Packet_Full_Name"] = gcs_tx_df["Packet_Name"].astype("str") + "-" + gcs_tx_df["Packet_Seq"].astype("str")
    # gcs_tx_packets = gcs_tx_df["Packet_Full_Name"].values
    # gcs_pd_df = gcs_pd_df.loc[gcs_pd_df["Packet_Name"].isin(gcs_tx_packets)]
    # uavs_tx_df["Packet_Full_Name"] = uavs_tx_df["Packet_Name"].astype("str") + "-" + uavs_tx_df["Packet_Seq"].astype("str")
    # uavs_tx_packets = uavs_tx_df["Packet_Full_Name"].values
    # uavs_pd_df = uavs_pd_df.loc[uavs_pd_df["Packet_Name"].isin(uavs_tx_packets)]

    # Instead of filtering out packets according to switch time, we consider only waypoint packets
    gcs_tx_df = gcs_tx_df.loc[['Waypoint' in name for name in gcs_tx_df.Packet_Name]]
    gcs_rx_df = gcs_rx_df.loc[['Waypoint' in name for name in gcs_rx_df.Packet_Name]]
    gcs_pd_df = gcs_pd_df.loc[['Waypoint' in name for name in gcs_pd_df.Packet_Name]]
    uavs_tx_df = uavs_tx_df.loc[['Waypoint' in name for name in uavs_tx_df.Packet_Name]]
    uavs_pd_df = uavs_pd_df.loc[['Waypoint' in name for name in uavs_pd_df.Packet_Name]]

    # Remember, the RX DFs in rx_df_list is [GCS, Gateway, UAV-0, UAV-1, ...]
    dl_num_rcvd = []
    dl_num_reliable = []
    dl_num_delay_excd = []
    for i in range(1,len(rx_df_list)):
        uav_rx_df = rx_df_list[i].copy()
        # uav_rx_df = uav_rx_df.loc[uav_rx_df["TxTime"] >= switch_time] # Filter by switch time
        uav_rx_df = uav_rx_df.loc[['Waypoint' in name for name in uav_rx_df.Packet_Name]] # Filter by packet name containing Waypoint
        if not uav_rx_df.empty:
            uav_rx_df["Delay"] = uav_rx_df['RxTime']-uav_rx_df['TxTime'] # Calc delay of packets received
            uav_rx_df_reliable = uav_rx_df.loc[(uav_rx_df["Delay"] <= dl_delay_threshold)]
            dl_num_rcvd.append(len(uav_rx_df)) 
            dl_num_reliable.append(len(uav_rx_df_reliable)) # Why not calc this from process_throughput_sliding_window_time_broadcast? Because of possibly overlapping time windows
            dl_num_delay_excd.append(len(uav_rx_df) - len(uav_rx_df_reliable))
        else:
            dl_num_rcvd.append(0)
            dl_num_reliable.append(0)
            dl_num_delay_excd.append(0)
    
    ''' Get metric of broadcast protocol '''
    # Downlink
    dl_reliability = []
    num_sent_dl = len(gcs_tx_df) # We are considering number of pkts sent (via broadcasting) by GCS to each UAV here
    for i in range(len(dl_num_reliable)):
        if num_sent_dl > 0:
            dl_reliability.append(dl_num_reliable[i] / num_sent_dl)
        else:
            dl_reliability.append(np.nan)

    # Uplink
    ul_num_reliable, ul_num_delay_excd, ul_num_incr_rcvd, ul_num_queue_overflow = count_packet_states(gcs_rx_df, uavs_pd_df, ul_delay_threshold)
    num_sent_ul = len(uavs_tx_df)
    if num_sent_ul > 0:
        total_reliability_ul = ul_num_reliable / num_sent_ul
    else:
        total_reliability_ul = np.nan

    return (run_number, dl_num_reliable, ul_num_reliable, dl_reliability, total_reliability_ul,
            dl_num_delay_excd, ul_num_delay_excd, ul_num_incr_rcvd, ul_num_queue_overflow)

if __name__ == "__main__":
    pd.options.mode.chained_assignment = None  # default='warn'

    sim_root_paths = ["/home/research-student/reuben_ws/FANET_Dataset/DJISpark_Obj3_Retransmission_Datasets/Waypoint_Only_UAV_Interference/uav_scenario_0", 
                      "/home/research-student/reuben_ws/FANET_Dataset/DJISpark_Obj3_Retransmission_Datasets/Waypoint_Only_UAV_Interference/uav_scenario_1", 
                      "/home/research-student/reuben_ws/FANET_Dataset/DJISpark_Obj3_Retransmission_Datasets/Waypoint_Only_UAV_Interference/uav_scenario_2", 
                      "/home/research-student/reuben_ws/FANET_Dataset/DJISpark_Obj3_Retransmission_Datasets/Waypoint_Only_MANET_Interference/manet_scenario_1",
                      "/home/research-student/reuben_ws/FANET_Dataset/DJISpark_Obj3_Retransmission_Datasets/Waypoint_Only_MANET_Interference/manet_scenario_a",
                      "/home/research-student/reuben_ws/FANET_Dataset/DJISpark_Obj3_Retransmission_Datasets/Waypoint_Only_MANET_Interference/manet_scenario_2"]
    save_paths = ["/home/research-student/reuben_ws/FANET_Dataset/DJISpark_Obj3_Retransmission_Datasets/Waypoint_Only_UAV_Interference/uav_scenario_0_processed",
                  "/home/research-student/reuben_ws/FANET_Dataset/DJISpark_Obj3_Retransmission_Datasets/Waypoint_Only_UAV_Interference/uav_scenario_1_processed",
                  "/home/research-student/reuben_ws/FANET_Dataset/DJISpark_Obj3_Retransmission_Datasets/Waypoint_Only_UAV_Interference/uav_scenario_2_processed",
                  "/home/research-student/reuben_ws/FANET_Dataset/DJISpark_Obj3_Retransmission_Datasets/Waypoint_Only_MANET_Interference/manet_scenario_1_processed",
                  "/home/research-student/reuben_ws/FANET_Dataset/DJISpark_Obj3_Retransmission_Datasets/Waypoint_Only_MANET_Interference/manet_scenario_a_processed",
                  "/home/research-student/reuben_ws/FANET_Dataset/DJISpark_Obj3_Retransmission_Datasets/Waypoint_Only_MANET_Interference/manet_scenario_2_processed"]
    switch_time_paths = ["/home/research-student/reuben_ws/omnet-fanet/obj3_scenario_script/uav_scenario_0/Switch_Details.csv",
                         "/home/research-student/reuben_ws/omnet-fanet/obj3_scenario_script/uav_scenario_1/Switch_Details.csv",
                         "/home/research-student/reuben_ws/omnet-fanet/obj3_scenario_script/uav_scenario_2/Switch_Details.csv",
                         "/home/research-student/reuben_ws/omnet-fanet/obj3_scenario_script/manet_scenario_1/Switch_Details.csv",
                         "/home/research-student/reuben_ws/omnet-fanet/obj3_scenario_script/manet_scenario_a/Switch_Details.csv",
                         "/home/research-student/reuben_ws/omnet-fanet/obj3_scenario_script/manet_scenario_2/Switch_Details.csv"]

    dl_delay_threshold = 1
    ul_delay_threshold = 1

    RUN_NUM = 499 # Max run number to consider, note it starts at 0

    for sim_root_path, save_path, switch_time_path in zip(sim_root_paths, save_paths, switch_time_paths):
        # Create save file directory if not created
        if not os.path.isdir(os.path.join(save_path)):
            os.mkdir(os.path.join(save_path))

        scenario_list = [f.path for f in os.scandir(sim_root_path) if f.is_dir()] # Get list of "unique" scenarios
        num_processes = 36
        # For each scenario, extract the UL and DL raw data
        for scenario_path in scenario_list:
            process_scenario_broadcast(scenario_path, save_path, switch_time_path, num_processes, dl_delay_threshold, ul_delay_threshold, RUN_NUM)


    
