'''
Date: 01/10/2024
Desc: For processing test cases for mitigation scheme where switching did not happen.
      This is to quantify run reliabilities of false negative predictions.
      This is just the first round of processing, further processing of results needed to get the false negatives.
'''

import pandas as pd # for data manipulation 
import numpy as np
# import matplotlib.pyplot as plt # for drawing graphs
import os, sys, glob, math
import time
from multiprocessing.pool import Pool
from itertools import repeat
from tqdm import tqdm
from scipy import special

def compile_micro_sim_data_v2(file_list, video=False):
    '''
    Function to compile data from the CSV files generated by each micro-simulation
    Update: To specifically return the rx_df, tx_df, mon_df and pd_df in lists, so that specific dfs can be accessed (instead of aggregating UAV dfs)
    Input: file_list - List of simulation files belonging to a certain scenario (micro-sim)
            video - flag to indicate whether to compile video data
    Output: concatenates the raw data to UL and DL dataframes
    '''
    # Specify dtypes to save memory
    tx_df_dtypes = {"TxTime": np.float32, "Packet_Name": "category", "Packet_Seq": np.uint32, "Bytes": np.uint16, "Dest_Addr": 'category'}
    rx_df_dtypes = {"RxTime": np.float64, "TxTime": np.float32,	"Packet_Name": "str", "Bytes": np.uint16, "RSSI": 'str', "U2G_SINR": np.float32, "U2U_SINR": np.float32, 
                    "U2G_BER": np.float32, "U2U_BER": np.float32, "Src_Addr": 'category', "Dest_Addr": 'category', "Hop_Count": np.uint8, "Delay": np.float32, 
                    "Queueing_Time": np.float32, "Backoff_Time": np.float32, "U2G_Distance": np.float32, "Retry_Count": np.uint8}
    pd_df_dtypes = {"RxTime": np.float64, "TxTime": np.float32,	"Packet_Name": "str", "Bytes": np.uint16, "RSSI": 'str', "U2G_SINR": np.float32, "U2U_SINR": np.float32, 
                    "U2G_BER": np.float32, "U2U_BER": np.float32, "Delay": np.float32, "Queueing_Time": np.float32, "Backoff_Time": np.float32, "U2G_Distance": np.float16,
                    "Has_Bit_Error": np.uint8, "Packet_Drop_Reason": 'category'}

    # Let's get the GCS dfs ===============================================================
    gcs_rx_file = [file for file in file_list if ('_GCS-Rx.csv' in file)]
    gcs_tx_file = [file for file in file_list if ('_GCS-Tx.csv' in file)]
    gcs_mon_file = [file for file in file_list if ('_GCS-Wlan.csv' in file)]
    gcs_pd_file = [file for file in file_list if ('_GCS-PacketDrop.csv' in file)]
    if len(gcs_rx_file) > 0:
        gcs_rx_df = pd.read_csv(gcs_rx_file[0], dtype=rx_df_dtypes)
    else:
        print("GCS RX File Missing")
        print(file_list[0])
    if len(gcs_tx_file) > 0:
        gcs_tx_df = pd.read_csv(gcs_tx_file[0], dtype=tx_df_dtypes)
    else:
        print("GCS TX File Missing")
        print(file_list[0])
    if len(gcs_pd_file) > 0:
        gcs_pd_df = pd.read_csv(gcs_pd_file[0], dtype=pd_df_dtypes)
    else:
        print("GCS PD File Missing")
        print(file_list[0])
    if len(gcs_mon_file) > 0:
        gcs_mon_df = pd.read_csv(gcs_mon_file[0]) # Mon file is optional
        gcs_mon_df["Addr"] = "192.168.0.1"
    else: 
        gcs_mon_df = None

    # Let's get the GW dfs ===============================================================
    gw_rx_file = [file for file in file_list if (('_GW-Rx' in file))]
    gw_tx_file = [file for file in file_list if (('_GW-Tx' in file))]
    gw_mon_file = [file for file in file_list if (('_GW-Wlan' in file))]
    gw_pd_file = [file for file in file_list if (('_GW-PacketDrop' in file))]
    if len(gw_rx_file) > 0:
        gw_rx_df = pd.read_csv(gw_rx_file[0], dtype=rx_df_dtypes)
    else:
        print("GW RX File Missing")
        print(file_list[0])
    if len(gw_tx_file) > 0:
        gw_tx_df = pd.read_csv(gw_tx_file[0], dtype=tx_df_dtypes)
    else:
        print("GW TX File Missing")
        print(file_list[0])
    if len(gw_pd_file) > 0:
        gw_pd_df = pd.read_csv(gw_pd_file[0], dtype=pd_df_dtypes)
    else:
        print("GW PD File Missing")
        print(file_list[0])
    if len(gw_mon_file) > 0:
        gw_mon_df = pd.read_csv(gw_mon_file[0]) # Mon file is optional
        gw_mon_df["Addr"] = "192.168.0.2"
    else:
        gw_mon_df = None

    # Let's get the UAVs dfs ===============================================================
    uavs_rx_df_list = []
    uavs_tx_df_list = []
    uavs_mon_df_list = []
    uavs_pd_df_list = []
    uav_rx_files = [file for file in file_list if (('_UAV-' in file) and ('-Rx' in file))]
    uav_tx_files = [file for file in file_list if (('_UAV-' in file) and ('-Tx' in file))]
    uav_mon_files = [file for file in file_list if (('_UAV-' in file) and ('Wlan' in file))]
    uav_pd_files = [file for file in file_list if (('_UAV-' in file) and ('PacketDrop' in file))]
    uav_rx_files.sort()
    uav_tx_files.sort()
    uav_mon_files.sort()
    uav_pd_files.sort()
    if len(uav_rx_files) > 0:
        for uav_rx_file in uav_rx_files:
            uavs_rx_df_list.append(pd.read_csv(uav_rx_file, dtype=rx_df_dtypes))
    else:
        print("UAV RX File(s) Missing")
        print(file_list[0])
    if len(uav_tx_files) > 0:
        for uav_tx_file in uav_tx_files:
            uavs_tx_df_list.append(pd.read_csv(uav_tx_file, dtype=tx_df_dtypes))
    else:
        print("UAV TX File(s) Missing")
        print(file_list[0])
    if len(uav_pd_files) > 0:
        for uav_pd_file in uav_pd_files:
            uavs_pd_df_list.append(pd.read_csv(uav_pd_file, dtype=pd_df_dtypes))
    else:
        print("UAV PD File(s) Missing")
        print(file_list[0])
    if len(uav_mon_files) > 0: # UAV mon files are optional now
        uav_member_index = 3
        for uav_mon_file in uav_mon_files:
            uav_mon_df = pd.read_csv(uav_mon_file)
            uav_mon_df["Addr"] = "192.168.0." + str(uav_member_index)
            uavs_mon_df_list.append(uav_mon_df)
            uav_member_index += 1
    else:
        uavs_mon_df_list = []

    rx_df_list = [gcs_rx_df, gw_rx_df] + uavs_rx_df_list
    tx_df_list = [gcs_tx_df, gw_tx_df] + uavs_tx_df_list
    pd_df_list = [gcs_pd_df, gw_pd_df] + uavs_pd_df_list
    mon_df_list = [gcs_mon_df, gw_mon_df] + uavs_mon_df_list

    # If video data available, compile it
    if video:
        gcs_video_rx_file = [file for file in file_list if ('_GCS-Video-Rx.csv' in file)]
        gw_video_tx_file = [file for file in file_list if ('_GW-Video-Tx.csv' in file)]
        gw_video_pd_file = [file for file in file_list if ('_GW-Video-PacketDrop.csv' in file)]
        if len(gcs_video_rx_file) > 0:
            gcs_video_rx_df = pd.read_csv(gcs_video_rx_file[0], dtype=rx_df_dtypes)
        else:
            print("GCS VIDEO RX File Missing")
            print(file_list[0])
        if len(gw_video_tx_file) > 0:
            gw_video_tx_df = pd.read_csv(gw_video_tx_file[0], dtype=tx_df_dtypes)
        else:
            print("GW VIDEO TX File Missing")
            print(file_list[0])
        if len(gw_video_pd_file) > 0:
            gw_video_pd_df = pd.read_csv(gw_video_pd_file[0], dtype=pd_df_dtypes)
        else:
            print("GW VIDEO PD File Missing")
            print(file_list[0])
        video_df_list = [gw_video_tx_df, gcs_video_rx_df, gw_video_pd_df] # For video packets

    if not video:
        return rx_df_list, tx_df_list, pd_df_list, mon_df_list
    else:
        return rx_df_list, tx_df_list, pd_df_list, mon_df_list, video_df_list

def count_packet_states(rx_df, pd_df, delay_threshold):
    """
    Desc: Count the number of reliable, delay excd, incr rcvd and q overflow packets for each micro-sim
    ASSUMPTION: The total number of packets in uavs_rx_df and gcs_pd_df makes up the total number of packets transmitted in downlink (gcs_tx_df)
                RETRY_LIMIT_REACHED is due to incorrectly received in downlink
    """
    # Make sure that the packets recorded as retry limit reach and queue overflow in pd_df are not in fact received in rx_df
    rx_packets = rx_df["Packet_Name"].values
    pd_df = pd_df.loc[~pd_df["Packet_Name"].isin(rx_packets)]

    delay = rx_df['RxTime']-rx_df['TxTime']
    num_reliable = np.sum(np.where(delay > delay_threshold , 0, 1))
    num_delay_excd = len(rx_df) - num_reliable
    pkt_drop_counts = pd_df["Packet_Drop_Reason"].value_counts()
    if len(pkt_drop_counts) > 2:
        print("ALERT: More than 2 packet drop reason found!")
    
    if "RETRY_LIMIT_REACHED" in pkt_drop_counts:
        num_incr_rcvd = pkt_drop_counts["RETRY_LIMIT_REACHED"]
    else:
        num_incr_rcvd = 0
    if "QUEUE_OVERFLOW" in pkt_drop_counts:
        num_queue_overflow = pkt_drop_counts["QUEUE_OVERFLOW"]
    else:
        num_queue_overflow = 0

    return num_reliable, num_delay_excd, num_incr_rcvd, num_queue_overflow
    
def process_run(run_number, scenario_path, dl_delay_threshold, ul_delay_threshold, vid_delay_threshold=0):
    '''
    Provide file_path such that the files for a particular run number can be identified using glob.glob(file_path.format(run_number))
    '''
    file_path = os.path.join(scenario_path, "Run-{}_*.csv")
    run_files = glob.glob(file_path.format(run_number)) # Get list of csv files belonging to this scenario

    if vid_delay_threshold == 0:
        rx_df_list, tx_df_list, pd_df_list, mon_df_list = compile_micro_sim_data_v2(run_files, video=False)
    elif vid_delay_threshold > 0:
        rx_df_list, tx_df_list, pd_df_list, mon_df_list, video_df_list = compile_micro_sim_data_v2(run_files, video=True)

    # Sort out which df is which
    # Remember, the RX DFs in rx_df_list is [GCS, Gateway, UAV-0, UAV-1, ...]
    gcs_rx_df = rx_df_list[0].copy()
    gcs_tx_df = tx_df_list[0]
    gcs_pd_df = pd_df_list[0]
    uavs_tx_df = pd.concat(tx_df_list[1:len(tx_df_list)], ignore_index=True) # Includes GW Tx DF and all UAVs Tx DFs
    uavs_rx_df = pd.concat(rx_df_list[1:len(rx_df_list)], ignore_index=True)
    uavs_pd_df = pd.concat(pd_df_list[1:len(pd_df_list)], ignore_index=True)

    # DL Metrics
    dl_num_reliable, dl_num_delay_excd, dl_num_incr_rcvd, dl_num_queue_overflow = count_packet_states(uavs_rx_df, gcs_pd_df, dl_delay_threshold)
    
    # UL Metrics
    ul_num_reliable, ul_num_delay_excd, ul_num_incr_rcvd, ul_num_queue_overflow = count_packet_states(gcs_rx_df, uavs_pd_df, ul_delay_threshold)
    
    # Get UL and DL metrics for each run
    num_dl_sent = len(gcs_tx_df)
    dl_reliability = dl_num_reliable / num_dl_sent
    num_ul_sent = len(uavs_tx_df)
    ul_reliability = ul_num_reliable / num_ul_sent

    # Get the throughput measures in video link based on time slots
    if vid_delay_threshold > 0:
        video_tx_df = video_df_list[0]
        video_rx_df = video_df_list[1]
        video_pd_df = video_df_list[2]
        vid_num_reliable, vid_num_delay_excd, vid_num_incr_rcvd, vid_num_queue_overflow = count_packet_states(video_rx_df, video_pd_df, vid_delay_threshold)
        # Get video metric for each run
        num_vid_sent = len(video_tx_df)
        vid_reliability = vid_num_reliable / num_vid_sent
    else:
        vid_reliability = np.nan
        vid_num_reliable = np.nan
        vid_num_delay_excd = np.nan
        vid_num_incr_rcvd = np.nan
        vid_num_queue_overflow = np.nan
        
    return (run_number, dl_reliability, dl_num_reliable, dl_num_delay_excd, dl_num_incr_rcvd, dl_num_queue_overflow, 
            ul_reliability, ul_num_reliable, ul_num_delay_excd, ul_num_incr_rcvd, ul_num_queue_overflow, 
            vid_reliability, vid_num_reliable, vid_num_delay_excd, vid_num_incr_rcvd, vid_num_queue_overflow)

def process_scenario_v4(scenario_path, save_path, switch_time_path, num_processes, 
                        dl_delay_threshold, ul_delay_threshold, vid_delay_threshold=0):
    '''
    Modified: To process all different runs of each sccenario 
    dl indicates Downlink. Likewise for ul (Uplink) and vid (Video)
    NOTE: If vid_delay_threshold = 0 (default), then the script will consider no video data to process!!!
    '''
    scenario = scenario_path.split("/")[-1]
    print(scenario)
    
    # UNCOMMENT BELOW TO ONLY PROCESS SCENARIOS WHERE THE SAVE_PATH DIR IS NOT YET CREATED
    # if os.path.isdir(os.path.join(save_path, scenario)):
    #     print("Skipping processed scenario")
    #     return

    # Get each simulation run from GCS-Tx.csv
    sim_run_list = sorted(glob.glob(os.path.join(scenario_path, "Run-*_GCS-Tx.csv")))
    run_num_list = [int(run.split('/')[-1].split("_")[0].split("-")[-1]) for run in sim_run_list]
    
    # Filter the run number, don't process runs listed in switch_time_df
    switch_time_df = pd.read_csv(switch_time_path)
    switch_time_df = switch_time_df.loc[switch_time_df["Scenario"]==scenario]
    if not switch_time_df.empty: 
        run_num_switch = switch_time_df["Run_Num"].astype('int').values # Get the run_number based on switch time (we only process runs where a switch to mitigation occured)
        run_num_no_switch = [run for run in run_num_list if run not in run_num_switch]
    else:
        run_num_no_switch = run_num_list # Process all runs
    # print(run_num_no_switch)
    # print(run_num_list)
    metric_list = []
    if len(run_num_no_switch) > 0:
        with Pool(num_processes) as pool:
            for result in pool.starmap(process_run, zip(run_num_no_switch, repeat(scenario_path), repeat(dl_delay_threshold), repeat(ul_delay_threshold),repeat(vid_delay_threshold))):
                metric_list.append({"Run": result[0], "Total_Reliability_DL": result[1], "Num_Pkts_Reliable_DL": result[2], "Num_Pkts_Delay_Excd_DL": result[3], "Num_Pkts_Incr_Rcvd_DL": result[4], "Num_Pkts_Q_Overflow_DL": result[5],
                                    "Total_Reliability_UL": result[6], "Num_Pkts_Reliable_UL": result[7], "Num_Pkts_Delay_Excd_UL": result[8], "Num_Pkts_Incr_Rcvd_UL": result[9], "Num_Pkts_Q_Overflow_UL": result[10],
                                    "Total_Reliability_VID": result[11], "Num_Pkts_Reliable_VID": result[12], "Num_Pkts_Delay_Excd_VID": result[13], "Num_Pkts_Incr_Rcvd_VID": result[14], "Num_Pkts_Q_Overflow_VID": result[15]})
        
    # Create save file directory if not created
    if not os.path.isdir(os.path.join(save_path, scenario)):
        os.mkdir(os.path.join(save_path, scenario))

    # Save metrics of each run to file
    if len(metric_list) > 0:
        metric_df = pd.DataFrame(metric_list)
    else:
        metric_df = pd.DataFrame(columns=['Run','Total_Reliability_DL','Num_Pkts_Reliable_DL','Num_Pkts_Delay_Excd_DL','Num_Pkts_Incr_Rcvd_DL','Num_Pkts_Q_Overflow_DL',
                                          'Total_Reliability_UL', "Num_Pkts_Reliable_UL", "Num_Pkts_Delay_Excd_UL", "Num_Pkts_Incr_Rcvd_UL", "Num_Pkts_Q_Overflow_UL", 
                                          "Total_Reliability_VID", "Num_Pkts_Reliable_VID", "Num_Pkts_Delay_Excd_VID", "Num_Pkts_Incr_Rcvd_VID", "Num_Pkts_Q_Overflow_VID"])
    metric_df.to_csv(os.path.join(save_path, scenario, "No_Switch_Results.csv"), index=False)

    return

if __name__ == "__main__":
    '''
    MAKE SURE TO SET "GX_GCS" and "sending_interval_range" in function process_sim_data_v2
    '''
    # sim_root_paths, save_paths, and switch_time_paths need to correspond to each other
    # switch_time_paths should only record runs where switching happened
    # Since when no switching happens, it is just manual control. Hence, just process from "Manual Control" results.
    sim_root_paths = ["/media/research-student/KingstonSSD/FANET_Dataset/DJISpark_Obj3_Retransmission_Datasets/Manual_UAV_Interference/uav_scenario_0", 
                      "/media/research-student/KingstonSSD/FANET_Dataset/DJISpark_Obj3_Retransmission_Datasets/Manual_UAV_Interference/uav_scenario_1", 
                      "/media/research-student/KingstonSSD/FANET_Dataset/DJISpark_Obj3_Retransmission_Datasets/Manual_UAV_Interference/uav_scenario_2",
                      "/media/research-student/KingstonSSD/FANET_Dataset/DJISpark_Obj3_Retransmission_Datasets/Manual_MANET_Interference/manet_scenario_0", 
                      "/media/research-student/KingstonSSD/FANET_Dataset/DJISpark_Obj3_Retransmission_Datasets/Manual_MANET_Interference/manet_scenario_1", 
                      "/media/research-student/KingstonSSD/FANET_Dataset/DJISpark_Obj3_Retransmission_Datasets/Manual_MANET_Interference/manet_scenario_2"]
    save_paths = ["/media/research-student/KingstonSSD/FANET_Dataset/DJISpark_Obj3_Retransmission_Datasets/Manual_UAV_Interference/uav_scenario_0_processed", 
                      "/media/research-student/KingstonSSD/FANET_Dataset/DJISpark_Obj3_Retransmission_Datasets/Manual_UAV_Interference/uav_scenario_1_processed", 
                      "/media/research-student/KingstonSSD/FANET_Dataset/DJISpark_Obj3_Retransmission_Datasets/Manual_UAV_Interference/uav_scenario_2_processed",
                      "/media/research-student/KingstonSSD/FANET_Dataset/DJISpark_Obj3_Retransmission_Datasets/Manual_MANET_Interference/manet_scenario_0_processed", 
                      "/media/research-student/KingstonSSD/FANET_Dataset/DJISpark_Obj3_Retransmission_Datasets/Manual_MANET_Interference/manet_scenario_1_processed", 
                      "/media/research-student/KingstonSSD/FANET_Dataset/DJISpark_Obj3_Retransmission_Datasets/Manual_MANET_Interference/manet_scenario_2_processed"]
    switch_time_paths = ["/home/research-student/omnet-fanet/data-processing-scripts/journal_3_scripts/switch_time/wp_uav_scenario_0_switch_time.csv", 
                         "/home/research-student/omnet-fanet/data-processing-scripts/journal_3_scripts/switch_time/wp_uav_scenario_1_switch_time.csv", 
                         "/home/research-student/omnet-fanet/data-processing-scripts/journal_3_scripts/switch_time/wp_uav_scenario_2_switch_time.csv",
                         "/home/research-student/omnet-fanet/data-processing-scripts/journal_3_scripts/switch_time/wp_manet_scenario_0_switch_time.csv", 
                         "/home/research-student/omnet-fanet/data-processing-scripts/journal_3_scripts/switch_time/wp_manet_scenario_1_switch_time.csv", 
                         "/home/research-student/omnet-fanet/data-processing-scripts/journal_3_scripts/switch_time/wp_manet_scenario_2_switch_time.csv"]

    dl_delay_threshold = 0.04
    ul_delay_threshold = 0.04
    vid_delay_threshold = 1 # NOTE: Set to zero if no video data

    for sim_root_path, save_path, switch_time_path in zip(sim_root_paths, save_paths, switch_time_paths):
        # Create save file directory if not created
        if not os.path.isdir(os.path.join(save_path)):
            os.mkdir(os.path.join(save_path))    

        scenario_list = [f.path for f in os.scandir(sim_root_path) if f.is_dir()] # Get list of "unique" scenarios
        num_processes = 32
        # For each scenario, extract the UL and DL raw data
        for scenario_path in scenario_list:
            process_scenario_v4(scenario_path, save_path, switch_time_path, num_processes, 
                                dl_delay_threshold, ul_delay_threshold, vid_delay_threshold)


    
