import pandas as pd # for data manipulation 
import numpy as np
# import matplotlib.pyplot as plt # for drawing graphs
import os, sys, glob, math
import time
from multiprocessing.pool import Pool
from itertools import repeat
from tqdm import tqdm
import xml.etree.ElementTree as ET
from bs4 import BeautifulSoup
import warnings

def compile_rx_sim_data(file_list):
    '''
    Function to compile data from the RX CSV files generated by each micro-simulation
    Modified from: compile_micro_sim_data_v2
    Basically, this function is the same as compile_micro_sim_data_v2 but for Rx data only
    Input: file_list - List of simulation files belonging to a certain scenario (micro-sim)
    Output: the RX DFs in rx_df_list is [GCS, Gateway, UAV-0, UAV-1, ...]
    '''
    # Specify dtypes to save memor
    rx_df_dtypes = {"RxTime": np.float64, "TxTime": np.float32,	"Packet_Name": "str", "Bytes": np.uint16, "RSSI": 'str', "U2G_SINR": np.float32, "U2U_SINR": np.float32, 
                    "U2G_BER": np.float32, "U2U_BER": np.float32, "Src_Addr": 'category', "Dest_Addr": 'category', "Hop_Count": np.uint8, "Delay": np.float32, 
                    "Queueing_Time": np.float32, "Backoff_Time": np.float32, "U2G_Distance": np.float32, "Retry_Count": np.uint8}

    # Let's get the GCS dfs ===============================================================
    gcs_rx_file = [file for file in file_list if ('_GCS-Rx.csv' in file)]
    if len(gcs_rx_file) > 0:
        gcs_rx_df = pd.read_csv(gcs_rx_file[0], dtype=rx_df_dtypes)
    else:
        print("GCS RX File Missing")
        print(file_list[0])

    # Let's get the GW dfs ===============================================================
    gw_rx_file = [file for file in file_list if (('_GW-Rx' in file))]
    if len(gw_rx_file) > 0:
        gw_rx_df = pd.read_csv(gw_rx_file[0], dtype=rx_df_dtypes)
    else:
        print("GW RX File Missing")
        print(file_list[0])

    # Let's get the UAVs dfs ===============================================================
    uavs_rx_df_list = []
    uav_rx_files = [file for file in file_list if (('_UAV-' in file) and ('-Rx' in file))]
    uav_rx_files.sort()
    if len(uav_rx_files) > 0:
        for uav_rx_file in uav_rx_files:
            try:
                uavs_rx_df_list.append(pd.read_csv(uav_rx_file, dtype=rx_df_dtypes))
            except Exception as e:
                print(uav_rx_file)
                print(e)
                assert False, "Error: {}".format(e)
    else:
        print("UAV RX File(s) Missing")
        print(file_list[0])

    rx_df_list = [gcs_rx_df, gw_rx_df] + uavs_rx_df_list

    return rx_df_list

def process_gamma_sliding_window_time(rx_df, delay_threshold, winSize, stride, max_time, uav_speed):
    '''
    Function to calculate N_r data for a DataFrame based on sliding window measured by time duration
    The sliding window will slide by "stride" seconds
    winSize is the sliding window size (in seconds)
    maxTime is the max simulation time to consider for calculating the throughput (seconds)
    rx_df - The reliable rcvd DF of interest
    uav_speed - UAV Speed, to calc the horizontal distance
    Return: A DataFrame of gamma (N_r/time_window_size) samples with its associated horizontal distance
    Modified: Before the first time window, use incremental window size (step size based on stride).
    ''' 
    gamma_list = []
    rcvd_df = rx_df.copy()
    rcvd_df["Delay"] = rcvd_df['RxTime'] - rcvd_df['TxTime'] # Calc delay of packets received
    rel_df = rcvd_df.loc[(rcvd_df["Delay"] <= delay_threshold)].copy() # Get DF of reliable packets

    # If the max time is less than window size, assert
    assert (max_time >= winSize), "Max Time should be greater than time window size"
   
    # Slide the time window        
    for i in range(math.floor((max_time - winSize) / stride) + 1): # Here, i*stride denotes the start of the time window
        rx_df_in_range = rel_df.loc[(rel_df["RxTime"] >= (i*stride)) & (rel_df["RxTime"] < (i*stride+winSize))] # Get rcvd packets within time window
        # Check if the time window does not exceed the max time. We only consider full time intervals
        if (i*stride+winSize) <= max_time:
            HDist = uav_speed * (i*stride+winSize)
            gamma = len(rx_df_in_range) / winSize
            
            gamma_list.append({"Time": i*stride+winSize, "Horizontal_Distance": HDist, "Gamma": gamma})

    return pd.DataFrame(gamma_list)

def process_scenario_v4(scenario_path, scenario_script_path, num_processes, 
                        dl_stride, ul_stride, dl_slot_size, ul_slot_size, dl_delay_threshold, ul_delay_threshold, 
                        dl_gamma_threshold, ul_gamma_thresholds):
    '''
    Modified: To process all different runs of each sccenario (for measured throughput while UAV moving)
    dl indicates Downlink. Likewise for ul (Uplink) and vid (Video)
    slot_size: the length of the slot size in seconds
    stride: The sliding window will slide by "stride" seconds
    ul_gamma_thresholds is a dict of gamma thresholds for different USI of UL
    '''
    scenario = scenario_path.split("/")[-1]

    print(scenario)
    scenario_params = scenario.split('_')
    height = float([param for param in scenario_params if "Height-" in param][0].split('-')[-1])
    hdist = float([param for param in scenario_params if "Distance-" in param][0].split('-')[-1])
    bitrate = float([param for param in scenario_params if "BitRate-" in param][0].split('-')[-1]) 
    uav_sending_interval = float([param for param in scenario_params if "UAVSendingInterval-" in param][0].split('-')[-1])
    uav_speed = float([param for param in scenario_params if "UAVSpeed-" in param][0].split('-')[-1]) 
    assert uav_speed > 0, "Mode slideWindow assumes UAVs are moving linearly with speed uav_speed, which cannot be 0"

    result_list = []
    runs = sorted(glob.glob("{}/Run-*_GCS-Tx.csv".format(scenario_path))) # Get the different runs for each scenario
    run_number = [run.split('/')[-1].split("_")[0].split("-")[-1] for run in runs]
    run_file_path = os.path.join(scenario_path, "Run-{}_*.csv")
    with Pool(num_processes) as pool:
        for result in pool.starmap(process_run, zip(run_number, repeat(run_file_path), repeat(scenario_script_path), repeat(height), repeat(uav_sending_interval), repeat(bitrate), repeat(uav_speed), repeat(hdist),
                    repeat(dl_stride), repeat(ul_stride), repeat(dl_slot_size), repeat(ul_slot_size), repeat(dl_delay_threshold), repeat(ul_delay_threshold),
                    repeat(dl_gamma_threshold), repeat(ul_gamma_thresholds[uav_sending_interval]))):
            result_list.append(result)
    # Save metrics of each run to file
    metric_df = pd.DataFrame(result_list)
    # metric_df.to_csv(os.path.join(scenario_script_path, "Switch_Details.csv"), index=False)

    return metric_df
    
def process_run(run_number, file_path, scenario_script_path, height, uav_sending_interval, bitrate, uav_speed, hdist,
                dl_stride, ul_stride, dl_slot_size, ul_slot_size, dl_delay_threshold, ul_delay_threshold,
                dl_gamma_threshold, ul_gamma_threshold):
    '''
    Provide file_path such that the files for a particular run number can be identified using glob.glob(file_path.format(run_number))
    '''

    run_files = glob.glob(file_path.format(run_number)) # Get list of csv files belonging to this scenario

    rx_df_list = compile_rx_sim_data(run_files) # Remember, the RX DFs in rx_df_list is [GCS, Gateway, UAV-0, UAV-1, ...]

    max_time = hdist / uav_speed # The max time for throughput measurement should be up to the simulation stop time
    
    uav_switch_time = [] #Record the switch times of all UAVs (np.inf for UAVs that did not switch)
    for i in range(1,len(rx_df_list)):
        uav_rx_df = rx_df_list[i].copy()
        if not uav_rx_df.empty:
            uav_gamma_df = process_gamma_sliding_window_time(uav_rx_df, dl_delay_threshold, dl_slot_size, dl_stride, max_time, uav_speed)
            # Get the time of first switch (if any)
            uav_gamma_fail_df = uav_gamma_df.loc[uav_gamma_df["Gamma"] < dl_gamma_threshold]
            if not uav_gamma_fail_df.empty:
                switch_time = uav_gamma_fail_df["Time"].min()
                uav_switch_time.append(switch_time)
                # if switch_time < uav_switch_time:
                #     uav_switch_time = switch_time
                #     uav_that_switch = i
            else:
                uav_switch_time.append(np.nan) 
        else: # If the UAV did not receive anything, switch at earliest time (t=1s)
            uav_switch_time.append(1)
    
    # Get the gamma measures in UL based on time slots
    gcs_rx_df = rx_df_list[0].copy()
    if not gcs_rx_df.empty:
        ul_gamma_df = process_gamma_sliding_window_time(gcs_rx_df, ul_delay_threshold, ul_slot_size, ul_stride, max_time, uav_speed)
        # Get the time of first switch (if any)
        ul_gamma_fail_df = ul_gamma_df.loc[ul_gamma_df["Gamma"] < ul_gamma_threshold]
        ul_switch_time = np.nan 
        if not ul_gamma_fail_df.empty:
            ul_switch_time = ul_gamma_fail_df["Time"].min()
    else: # If the GCS did not receive anything, switch at earliest time (t=1s)
        ul_switch_time = 1

    # Let's record all the switch times in scenario script files
    with warnings.catch_warnings():
        warnings.filterwarnings('ignore', r'All-NaN axis encountered')
        if ~np.isnan(np.nanmin(uav_switch_time)) and ~np.isnan(ul_switch_time): # Check if switching happened at all
            scenario = ET.Element('scenario') # <set-param t="1.5" module="gatewayNode.app[0]" par="control_mode" value="1"/>
            if ~np.isnan(ul_switch_time):
                set_param = ET.SubElement(scenario, 'set-param', attrib={"t": str(ul_switch_time), "module":"{}.app[0]".format("GCS"), "par":"control_mode", "value":"1"})
            if ~np.isnan(uav_switch_time[0]):
                set_param = ET.SubElement(scenario, 'set-param', attrib={"t": str(uav_switch_time[0]), "module":"{}.app[0]".format("gatewayNode"), "par":"control_mode", "value":"1"})
            for i in range(1,len(uav_switch_time)):
                if ~np.isnan(uav_switch_time[i]):
                    set_param = ET.SubElement(scenario, 'set-param', attrib={"t": str(uav_switch_time[i]), "module":"{}.app[0]".format("adhocNode[{}]".format(i-1)), "par":"control_mode", "value":"1"})
            
            # if (ul_switch_time <= uav_switch_time): # GCS Initiated Switch
            #     overall_switch_time = ul_switch_time
            #     node_name = 'GCS'
            # else: # UAV Initiated Switch
            #     overall_switch_time = uav_switch_time
            #     if (uav_that_switch == 1):
            #         node_name = "gatewayNode"
            #     else:
            #         node_name = "adhocNode[{}]".format(uav_that_switch-2) # Minus 2 because index 1 correspond to gateway, and 2 onwards correspond to UAVs onwards
            # result = {"Run": run_number, "Node_Switch": node_name, "Switch_Time": overall_switch_time, "Height": height, "USI": uav_sending_interval, "Bit_Rate": bitrate, "UAV_Speed": uav_speed}
            # scenario = ET.Element('scenario') # <set-param t="1.5" module="gatewayNode.app[0]" par="control_mode" value="1"/>
            # at = ET.SubElement(scenario, 'at', t=str(overall_switch_time))
            # set_param = ET.SubElement(at, 'set-param', attrib={"module":"{}.app[0]".format(node_name), "par":"control_mode", "value":"1"})
        else: # No switching happened
            # In this case just "switch" at t = 0s
            scenario = ET.Element('scenario') # <set-param t="1.5" module="gatewayNode.app[0]" par="control_mode" value="1"/>
            at = ET.SubElement(scenario, 'at', t=str(0.1)) # t=0 will cause errors!
            set_param = ET.SubElement(at, 'set-param', attrib={"module":"GCS.app[0]", "par":"control_mode", "value":"1"})
            set_param = ET.SubElement(at, 'set-param', attrib={"module":"gatewayNode.app[0]", "par":"control_mode", "value":"1"})
            for i in range(2,len(rx_df_list)):
                set_param = ET.SubElement(at, 'set-param', attrib={"module":"adhocNode[{}].app[0]".format(i-2), "par":"control_mode", "value":"1"})
        
    # Write the XML File for Scenario Scripting
    scenario_script = ET.ElementTree(scenario)
    scenario_script = BeautifulSoup(ET.tostring(scenario_script.getroot(), 'utf-8'), features="html.parser")
    with open(os.path.join(scenario_script_path, 'height-{}_usi-{}_bitrate-{}_uavspeed-{}_run-{}_scenario_script.xml'.format(height, uav_sending_interval, bitrate, uav_speed, run_number)), 'w') as f:
        f.write(scenario_script.prettify())

    result = {"Run": run_number, "Height": height, "USI": uav_sending_interval, "Bit_Rate": bitrate, "UAV_Speed": uav_speed,
            "GCS_Switch_Time": ul_switch_time, "GW_Switch_Time": uav_switch_time[0], "UAV_0_Switch_Time": uav_switch_time[1], 
            "UAV_2_Switch_Time": uav_switch_time[2], "UAV_3_Switch_Time": uav_switch_time[3], "UAV_4_Switch_Time": uav_switch_time[4], 
            "UAV_5_Switch_Time": uav_switch_time[5], "UAV_6_Switch_Time": uav_switch_time[6], "UAV_7_Switch_Time": uav_switch_time[7]}
    
    return result

if __name__ == "__main__":

    sim_root_paths = ["/home/clow0003/Reuben_ws/FANET_Dataset/DJISpark_Obj3_Retransmission_Datasets/Manual_UAV_Interference_new/uav_scenario_0",
                    "/home/clow0003/Reuben_ws/FANET_Dataset/DJISpark_Obj3_Retransmission_Datasets/Manual_UAV_Interference_new/uav_scenario_1",
                    "/home/clow0003/Reuben_ws/FANET_Dataset/DJISpark_Obj3_Retransmission_Datasets/Manual_UAV_Interference_new/uav_scenario_2",
                    "/home/clow0003/Reuben_ws/FANET_Dataset/DJISpark_Obj3_Retransmission_Datasets/Manual_MANET_Interference_new/manet_scenario_1",
                    "/home/clow0003/Reuben_ws/FANET_Dataset/DJISpark_Obj3_Retransmission_Datasets/Manual_MANET_Interference_new/manet_scenario_a",
                    "/home/clow0003/Reuben_ws/FANET_Dataset/DJISpark_Obj3_Retransmission_Datasets/Manual_MANET_Interference_new/manet_scenario_2"]
    scenario_script_paths = ["/home/clow0003/Reuben_ws/obj3_scenario_script_new/uav_scenario_0",
                            "/home/clow0003/Reuben_ws/obj3_scenario_script_new/uav_scenario_1",
                            "/home/clow0003/Reuben_ws/obj3_scenario_script_new/uav_scenario_2",
                            "/home/clow0003/Reuben_ws/obj3_scenario_script_new/manet_scenario_1",
                            "/home/clow0003/Reuben_ws/obj3_scenario_script_new/manet_scenario_a",
                            "/home/clow0003/Reuben_ws/obj3_scenario_script_new/manet_scenario_2"]

    ul_gamma_thresholds = {10: 752, 20: 376, 66.7: 114, 100: 78}
    dl_gamma_threshold = 48

    dl_slot_size = 1 # Either the length of time slots, or the sliding window size. For count, this is the timeDiv
    ul_slot_size = 1 # Either the length of time slots, or the sliding window size
    vid_slot_size = 1 # Either the length of time slots, or the sliding window size

    # ''' Manual Control Mode '''
    dl_delay_threshold = 0.04
    ul_delay_threshold = 0.04
    vid_delay_threshold = 1 # NOTE: Set to zero if no video data
    dl_stride = 0.1 # 100ms stride
    ul_stride = 0.1 # 100ms stride
    vid_stride = 0.1 # 100ms stride

    for sim_root_path, scenario_script_path in zip(sim_root_paths, scenario_script_paths):
        # Create save file directory if not created
        if not os.path.isdir(scenario_script_path):
            os.mkdir(scenario_script_path)    

        scenario_list = [f.path for f in os.scandir(sim_root_path) if f.is_dir()] # Get list of "unique" scenarios
        num_processes = 36
        scenario_switch_df_list = []
        for scenario_path in scenario_list:
            switch_df = process_scenario_v4(scenario_path, scenario_script_path, num_processes, 
                                dl_stride, ul_stride, dl_slot_size, ul_slot_size, dl_delay_threshold, ul_delay_threshold, 
                                dl_gamma_threshold, ul_gamma_thresholds)
            scenario_switch_df_list.append(switch_df)
        
        scenario_switch_df = pd.concat(scenario_switch_df_list)
        scenario_switch_df.to_csv(os.path.join(scenario_script_path, "Switch_Details.csv"), index=False)

