#!/bin/env bash

#SBATCH --job-name=fanet_rebroadcast_uav_manet_interference
#SBATCH --time=168:00:00
#SBATCH --mem=32000
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=64
#SBATCH --partition=cpu1.medm,cpu2,cpu1,cpu1.largem

# # Rebroadcast UAV
# opp_runall -j64 ../src/fanet -m -u Cmdenv -c Rebroadcast_UAV_Int -n .:../src:../../inet4.5/examples:../../inet4.5/showcases:../../inet4.5/src:../../inet4.5/tests/validation:../../inet4.5/tests/networks:../../inet4.5/tutorials --image-path=../../inet4.5/images -l ../../inet4.5/src/INET \
# --cmdenv-redirect-output=false --record-eventlog=false --scalar-recording=false --vector-recording=false --cmdenv-express-mode=true --cmdenv-stop-batch-on-error=true \
# fanet_rebroadcast_uav_int_01112024.ini
# if [ $? -ne 0 ]; then  
#     echo "Error in Rebroadcast_UAV_Int fanet_rebroadcast_uav_int_01112024"  
#     exit 1
# fi

# # Rebroadcast MANET
# opp_runall -j64 ../src/fanet -m -u Cmdenv -c Rebroadcast_MANET_Int -n .:../src:../../inet4.5/examples:../../inet4.5/showcases:../../inet4.5/src:../../inet4.5/tests/validation:../../inet4.5/tests/networks:../../inet4.5/tutorials --image-path=../../inet4.5/images -l ../../inet4.5/src/INET \
# --cmdenv-redirect-output=false --record-eventlog=false --scalar-recording=false --vector-recording=false --cmdenv-express-mode=true --cmdenv-stop-batch-on-error=true \
# fanet_rebroadcast_manet_int_04112024.ini
# if [ $? -ne 0 ]; then  
#     echo "Error in Rebroadcast_MANET_Int fanet_rebroadcast_manet_int_04112024"  
#     exit 1
# fi

# GCS Rebroadcast UAV
opp_runall -j64 ../src/fanet -m -u Cmdenv -c GCS_Rebroadcast_UAV_Int -n .:../src:../../inet4.5/examples:../../inet4.5/showcases:../../inet4.5/src:../../inet4.5/tests/validation:../../inet4.5/tests/networks:../../inet4.5/tutorials --image-path=../../inet4.5/images -l ../../inet4.5/src/INET \
--cmdenv-redirect-output=false --record-eventlog=false --scalar-recording=false --vector-recording=false --cmdenv-express-mode=true --cmdenv-stop-batch-on-error=false \
fanet_rebroadcast_uav_int_01112024.ini
if [ $? -ne 0 ]; then  
    echo "Error in GCS_Rebroadcast_UAV_Int fanet_rebroadcast_uav_int_01112024"  
    exit 1
fi

# GCS Rebroadcast MANET
opp_runall -j64 ../src/fanet -m -u Cmdenv -c GCS_Rebroadcast_MANET_Int -n .:../src:../../inet4.5/examples:../../inet4.5/showcases:../../inet4.5/src:../../inet4.5/tests/validation:../../inet4.5/tests/networks:../../inet4.5/tutorials --image-path=../../inet4.5/images -l ../../inet4.5/src/INET \
--cmdenv-redirect-output=false --record-eventlog=false --scalar-recording=false --vector-recording=false --cmdenv-express-mode=true --cmdenv-stop-batch-on-error=false \
fanet_rebroadcast_manet_int_04112024.ini
if [ $? -ne 0 ]; then  
    echo "Error in GCS_Rebroadcast_MANET_Int fanet_rebroadcast_manet_int_04112024"  
    exit 1
fi
